### PR TITLE
Add experimental BatchMatMul operator

### PR DESCRIPTION
**Pull request by jamesr66a**
This is needed for fairseq-py. Seems like a pretty common operation

### CODE REVIEW

**Comment by jamesr66a** [comment]
Hi Emad, Can you provide an example of the case [C, M, K] * [C, K, N] -> [C, M, N] with the Numpy dot api?

**Comment by ebarsoum** [comment]
The current Dot is wrong, in our latest discussion we decided to replace it with MatMul that support numpy semantic. In numpy more than 2D, it treated as stacked matrices.  So what you provided should work.

Here the proposal, remove dot and rename BatchMatMul to MatMul, and make it behave like numpy for up to 3D. No need to support more than that.

If both inputs are <= 2D, then it is simply a matrix multiplication. If one or both are 3D, then the third dimension is the batch axis and will act as simply stacking multiple 2D tensors. If we want a batch of 1D, then we can reshape them to  [C, 1, K] * [C, K, 1] -> [C, 1, 1]. This will cover the case, where one has batch axis and the other not.

**Comment by ezyang** [comment]
@ebarsoum So, if I understand you correctly, you don't want a BatchMatMul in ONNX (whose semantics would be equivalent to `np.matmul` even for N > 3), because you want exporters to reshape, matrix multiply, and then unreshape?

Now that I am thinking about this, there is one practical problem to doing it this way. Something that we've been trying to support is ONNX models which are flexible with regards to their batch size, i.e., one of these dynamic dimensions we've been talking about. But now we are in trouble: a reshape operation takes hard coded integers for the shape to reshape. So the initial reshape is OK because you can use -1 to infer the dimensions you need, but you're a bit stuck for restoring the shape, because you need to know what the batch size was to write it in, but that's dynamic.

Have you guys thought about how to solve this problem at all?

**Comment by ebarsoum** [comment]
@ezyang how BatchMatMul is equivalent to np.matmul for N > 3, I through BatchMatMul always treat only first dimension as batch, right and only support 3D? np.matmul always treat last 2 dimension as matrix.

What I am asking is that is there a reason to have both MatMul and BatchMatMul (I am reading their behavior from Caffe 2) instead of combining them into one. If we follow numpy semantic it should support both cases, right? especially the case, where one operand have batch axis and the other doesn't (W*x). The reason that I said we can stop at 3D, because we don't have a case for more than 1D batch axes (sequences is another story) and we can expand them in the future.

Regarding the reshape problem this is why in CNTK batch axis isn't index based, we treat it specially and directly reference it by name. Which help is the case that you mentioned. We actually don't support batch axis with fixed size.

**Comment by ezyang** [comment]
@ebarsoum  I'm sorry! I was totally misinformed about the semantics of `torch.bmm`, from whom the proposed `BatchMatMul` inherited its semantics; I thought bmm supported > 3D, but it doesn't. So, the situation I described, is actually for the *opposite* situation of what `MatMul` is: the MatMul that supports n-dimensional batching is the GOOD situation, and having only the 3D MatMul is the BAD situation.

@jamesr66a So, actually, the motivation for `BatchMatMul` is a bit different than what we originally expected. I thought that `BatchMatMul` wasn't going to be supported by `MatMul`, but a `BatchMatMul` call is translatable to `MatMul` in the obvious way (just swap `BatchMatMul` with `MatMul`

The actual problem is onnx-caffe2 side, for *implementing* generalized MatMul (cc @bddppq). The trouble is Caffe2's `BatchMatMul` only supports 3D inputs. So, to implement the general numpy style MatMul, we must reshape the tensor to 3D, and then shape it back. But the exporter doesn't have the info needed to actual do this conversion.

I don't know if "Caffe2 doesn't implement general Numpy semantics" is a good reason to change the ONNX spec, but it is definitely a technical problem on our side.

**Comment by bddppq** [comment]
Adding support for >3D in Caffe2 BatchMatMul:  https://github.com/caffe2/caffe2/pull/1399

**Comment by ebarsoum** [comment]
@bddppq I am ok with more than 3D, the reason that I said up to 3D initially, because you already have implementation for it in both Caffe 2 and PyTorch.

Are you guys all ok, to have one MatMul that matches numpy semantic? So no Dot, No BatchMatMul.

**Comment by jamesr66a** [comment]
@ebarsoum Your proposal sounds reasonable, the only thing I'm concerned about is that MatMul in caffe2 has (undocumented) semantics whereby leftmost dimensions are collapsed (also rightmost dimensions are collapsed but that's immaterial to the batching situtation). So for example I can have `[a, b, c] * [a, b, c]` with axis_a=2, axis_b=2, trans_b=1 yield `[a*b, c] * [c, a*b] -> [a*b, a*b]`. This behavior is convenient because reshapes happen implicitly and allows for the case of `a` or `b` being dynamically shaped, which becomes a problem when you have to Reshape back with an op that only supports statically-defined shapes.

How about this: we have a single MatMul operator that supports N-dimensional A and B tensors. But as arguments, we have `axis_a`, `axis_b`, `batch_a`, and `batch_b`. `axis` arguments specify where to partition left and right dimensions (e.g. [a, b, c] axis=2 specifies [a*b, c]), and as a layer on top of that `batch` arguments specify the right-most dimension that is included in the batch (default -1). So [a, b, c] axis=2, batch=0 treats the tensor as a batch of `b*c` sized tensors, containing `a` of them. Afaict this should cover batching as well as collapsing as well as obviate the need for preserving dimensions to un-reshape.

**Comment by dzhulgakov** [comment]
Hm, actually C2 behavior is inconsistent between FC and MatMul:
https://github.com/caffe2/caffe2/blob/master/caffe2/operators/matmul_op.cc#L47
https://github.com/caffe2/caffe2/blob/master/caffe2/operators/fully_connected_op.h#L87

-> MatMul doesn't reshape back.

In this particular case I'm inclined not to overcomplicate things and actually drop the axis part from MatMul in ONNX - it's probably not used that often. What do you think?

**Comment by bddppq** [comment]
I agree onnx MatMul should not have axis attributes and should simply follow the numpy semantic.
In Caffe2, for backward compatibility we can not change MatMul to behave the same, but actually BatchMatMul's current functionality is a strict subtset of numpy matmul, we can extend it to be the numpy matmul equivalent so onnx-caffe2 can simply pass through.

**Comment by ebarsoum** [comment]
Agree with @bddppq , let's follow numpy semantic.

**Pull request closed without merging**
