### PR TITLE
Fix function finding for python binding

### PR DESCRIPTION
**Pull request by take-cheeze**
### Description

`GetFunction()` may return `nullptr` so let's fix finding for now
closes https://github.com/onnx/onnx/issues/4703

### CODE REVIEW

**Review by liqunfu — APPROVED** [review]
thank you for fixing this @take-cheeze

**Comment by take-cheeze** [comment]
Seems CI is failing with `ref_attr_name` extraction https://github.com/onnx/onnx/blob/ee7d2cdfa34b8b3c7e0b68b70daf72aaa48c23ac/onnx/onnx.proto#L144

**Comment by take-cheeze** [comment]
https://github.com/onnx/onnx/pull/4710 was merged and code styling should be fixed so CI is all happy now :)

**Comment by jcwchen** [comment]
Thanks for the reminder! @onnx/sig-operators-approvers could you please review/approve it?

**Review by gramalingam — APPROVED** [review]

**Review by xadupre — APPROVED** [review]

**Pull request merged**
