### PR TITLE
Expose model parser API in Python (onnx.parser)

### PR DESCRIPTION
**Pull request by gramalingam**
**Description**
Export parser methods (for model and graph) to python.

**Motivation and Context**
Allows python code to use parser to construct models.

### CODE REVIEW

**Comment by askhade** [comment]
Parser does not handle multiple opset imports "opset_import: [ "" : 13, "custom_domain" : 1]" the comma between the 2 opsets does not work... it requires "opset_import: [ "" : 13 "custom_domain" : 1],". Can you please fix this.

**Comment by askhade** [comment]
Can you add some documentation around usage for python apis

**Comment by askhade** [comment]
Please add some tests

**Review by askhade — APPROVED** [review]

**Comment by askhade** [comment]
@gramalingam 

1. Can you fix the lgtm-bot error
2. FunctionVerification.VerifyModelLocalFunctions is failing in CIs, this is because this test imports opsets without "," as a separator this needs to be fixed along with your fix for parser to allow "," as a separator between multiple opset imports

**Comment by gramalingam** [comment]
@postrational @wschin @ebarsoum : any feedback on this PR? Thanks!

**Review by postrational — APPROVED** [review]

**Pull request merged**
