### PR TITLE
Support node labels in parser and printer

### PR DESCRIPTION
**Pull request by gramalingam**
### Description

1) Adds support for node label in parser and printer
2) Adds some status-checks that were missed in recent addition to support invalid identifiers.

Node labels are now supported with the following syntax:

```
   [a_node_label] y = MatMul (x, w)
```

However, we have a couple of options to choose from here:

(a) The ONNX spec says that the node label must be a valid identifier. So, we can allow for a valid identifier between the `[...]`, relying on a quoted string inside if the user wants to use something that is not a valid identifier.

(b) Alternatively, since `[` and `]` act as end-markers, like quotes, we can allow any string in-between, that is taken to be the node label. (Users will need to use an escape backslash if they want `]` in the label.)

Option (b) is better if users want to use non-identifier labels, eg., numbers, etc. I am inclined to go with (b), even though it is extra code. However, it won't be friendly to the use of white-space inside if users want to use identifier labels. Eg., `[ mylabel ]` will include the blank spaces in the label.

The implementation currently does only (a), which is simpler.

### CODE REVIEW

**Comment by justinchuby** [comment]
- Would quoting the label be too extra, as in `[ "some node" ]` (hopefully not)?
- Would it be a bad idea to put the label to the end of the line, so that varying length labels will not make the lines look weird? For example

```
[ some_label ] y = Add (x, y)
[ some_extra_extra_long_label__some_scope_1__some_scope_2 ] z = some::SomeNodeNames(y)
```

Or does this syntax support line breaks, so
```
[ some_label ]
y = Add (x, y)
[ some_extra_extra_long_label__some_scope_1__some_scope_2 ]
z = some::SomeNodeNames(y)
```

is valid?

**Comment by gramalingam** [comment]
> * Would quoting the label be too extra, as in `[ "some node" ]` (hopefully not)?

Yes ... that is precisely the choice/tradeoff discussed between (a) and (b). Option (b) avoids it, at the cost of including any extra blanks before or after the label as part of the label. (Though we could skip that, but seems a bit complicated).

Yes, line breaks can be used.

Putting the labels at the end: hmmm. It has the advantage you mention. But it seems less natural (convention typically puts labels before the statement; and, with if/while this would push the label to appear after the entire if/while body). I am inclined to leave it as is (visualization tools can always choose to present it differently, with alignment/omission etc. being supported as pretty-printing options).

**Comment by justinchuby** [comment]
I see. "some node" is a valid identifier. I missed that part.

**Review by justinchuby — APPROVED** [review]

**Comment by gramalingam** [comment]
> I see. "some node" is a valid identifier. I missed that part.

I am unclear what your preference is. I am planning to extend the PR to allow `[some node]` as opposed to the current requirement of `["some node"]`. Please let me know if you think that's not a good idea.

**Comment by justinchuby** [comment]
I think it would be more straightforward to just assume a valid identifier so that it is consistent across

**Comment by justinchuby** [comment]
Sorry I see the trade off now: node names may not be a valid identifier…

**Comment by gramalingam** [comment]
Ok, I will leave this as is (using option 1).

**Pull request merged**
