### PR TITLE
Add Where op.

### PR DESCRIPTION
**Pull request by kit1980**

### CODE REVIEW

**Comment by kit1980** [comment]
@zrphercule, there is an issue suggesting using If: https://github.com/onnx/onnx/issues/870
But as I mentioned there, it's not possible to use it for Where because you don't just select one of the output tensors, you select some elements from the first tensor, and some elements from the second tensor. And if there is only one input, Where returns indices of true elements.

I'll update with regenerated docs and test data.

**Comment by liqunfu** [comment]
Please update onnx/defs/operator_sets.h with the new op

**Comment by gramalingam** [comment]
The two usage scenarios (one where X and Y are specified and one where X and Y are not specified) seem different. Why bundle them into one op? I understand numpy does it, but should we duplicate the same? Why not make these different ops? It is easier to describe/implement/understand when they are separate.

**Comment by kit1980** [comment]
@gramalingam Tensorflow also has the dual-intent Where as numpy. With two different ops, we'll need to invent some non-standard name for one variant.

**Comment by gramalingam** [comment]
Ok. I think it would help to clarify in the documentation what happens when X and Y are not specified: e.g., "returns the indices of positions in the first tensor where the value is 1, as a 2 dimensional tensor where the first index is … and second index is ...".  It looks like the shape you specify for output has the two dimensions in the opposite order to what is in tensorflow. Adding a shape inference function for the op would also be helpful.

**Comment by kit1980** [comment]
Modified the Where op spec to accept only three arguments (the one argument case is to be handled by NonZero). Also added shape and type inference.

**Comment by kit1980** [comment]
A separate PR for NonZero: https://github.com/onnx/onnx/pull/1714

**Comment by kit1980** [comment]
Can someone look at this? The Where Op is much simpler now.

**Comment by kit1980** [comment]
Rebased on master.

**Pull request merged**
