### PR TITLE
Fix some examples for ArgMax

### PR DESCRIPTION
**Pull request by yihonglyu**
- test_argmax_no_keepdims_example
- test_argmax_default_axis_example
- test_argmax_no_keepdims_example_select_last_index

Signed-off-by: Yi-Hong Lyu <yilyu@microsoft.com>

### CODE REVIEW

**Review by jcwchen — COMMENTED** [review]
Thank you for the fix! Please update the documents (`docs/Operators.md ` and ` docs/TestCoverage.md`) as well by using `python onnx\defs\gen_doc.py` and `python onnx\backend\test\stat_coverage.py` since they use the test code in the docs.

Reference: [CONTRIBUTING.md](https://github.com/onnx/onnx/blob/master/docs/CONTRIBUTING.md#generated-operator-documentation)

**Comment by yihonglyu** [comment]
Updated docs/Operators.md and docs/TestCoverage.md

**Comment by jcwchen** [comment]
> Updated docs/Operators.md and docs/TestCoverage.md

Awesome! Now they pass CIs. Last thing, please sign-off the latest commit as well. Every commit in ONNX needs to be sign-off. Thank you!

**Comment by yihonglyu** [comment]
I rebase -i the commits and there is only one sign-off commit now.

**Review by jcwchen — APPROVED** [review]
LGTM. Thank you for catching this!

**Review by askhade — APPROVED** [review]

**Pull request merged**
