### PR TITLE
Fix errors in RoiAlign shape inference code

### PR DESCRIPTION
**Pull request by gramalingam**
Fix errors in RoiAlign shape inference. The existing version has the following issues:
(a) It assumes that the attributes for height and width are present, but they are optional. This will cause a null-dereference.
(b) It assumes that the input-shape dimensions are all known values, but they could be unknown or symbolic dimensions. This will cause output dimensions to be inferred as zero incorrectly.

This PR also adds shape-inference-tests to catch above two issues.

This PR also adds some utility functions to help simplify writing shape-inference.

### CODE REVIEW

**Comment by gramalingam** [comment]
Close and reopen to trigger CI

**Comment by gramalingam** [comment]
I hadn't noticed that @hariharans29 had already created a PR for shape-inference for the same op at https://github.com/onnx/onnx/pull/2133 : I will talk with him to resolve these PRs.

**Comment by gramalingam** [comment]
I had an offline discussion with Hari. The purpose of the current PR is to introduce unification utilities to help simplify our shape-inference code. It uses RoiAlign to illustrate the usage. Hari offered to reconcile these changes with his own PR. @hariharans29 : please take a look at this PR, thanks.

**Comment by hariharans29** [comment]
Looks good. The simple helpers make it easy to review the overall logic :). I will try and adopt these in my PRs and contribute more helpers if need be. Thanks!

**Pull request merged**
