### PR TITLE
Remove unnecessary import

### PR DESCRIPTION
**Pull request by xadupre**
Signed-off-by: xadupre <xadupre@microsoft.com>

### Description

Remove unnecessary import, shorten a few very long line.

### Motivation and Context

Better code.

### CODE REVIEW

**Review by jcwchen — COMMENTED** [review]
Thanks for catching this. It's something I would like to solve as well and this PR has partially covered it: https://github.com/onnx/onnx/pull/4467. Since that PR also covers other things, perhaps we can merge this one first.

**Comment by xadupre** [comment]
The overlap seems small. It should be ok either way.

**Comment by xadupre** [comment]
@jcwchen the PR is ready to reviewed. black should prevent any merging issue.

**Review by jcwchen — APPROVED** [review]
LGTM. Thanks for improving!

**Review by gramalingam — APPROVED** [review]

**Pull request merged**
