### PR TITLE
Fix the description of training_mode in BatchNormalization

### PR DESCRIPTION
**Pull request by Cecilwang**
The description of training_mode in BatchNormalization doesn't match the number of outputs

### CODE REVIEW

**Comment by xadupre** [comment]
You need to regenerate `Operators.md`.

**Review by jcwchen — COMMENTED** [review]
I will run auto update doc CI to generate documents for you.

**Comment by justinchuby** [comment]
@Cecilwang could you follow https://github.com/onnx/onnx/pull/5288/checks?check_run_id=16356889127 to signoff all commmits? Thanks!

**Comment by justinchuby** [comment]
Bump

**Comment by gramalingam** [comment]
Replacing this by new PR #5932

**Comment by gramalingam** [comment]
Replacing this by new PR https://github.com/onnx/onnx/pull/5932

**Pull request closed without merging**
