### PR TITLE
(WIP) local function inline

### PR DESCRIPTION
**Pull request by liqunfu**
Signed-off-by: Liqun Fu <liqfu@microsoft.com>

**Description**
- Describe your changes.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by justinchuby** [comment]
@titaiwangms

**Comment by titaiwangms** [comment]
@

> @titaiwangms

@justinchuby I think this is exactly what we need for new symbolic_fn. We should proceed on this if ONNX team is busy with other stuff? What do you think?

**Comment by justinchuby** [comment]
I don't know if the same features are being worked on in other prs? @liqunfu @gramalingam could you share some context on where we are in inlining features?

**Comment by gramalingam** [comment]
This does look outdated. Do we really need this, given that we have one implementation of inliner in place already?

**Pull request closed without merging**
