### PR TITLE
function registration refactor.

### PR DESCRIPTION
**Pull request by linkerzhang**
More APIs may be added into FunctionBuilderRegistry for different accessing patterns. I'll change OpSchemaRegistry following this pattern to remove those "abort()" function call.

### CODE REVIEW

**Comment by bddppq** [comment]
Can we simply change from calling abort to throwing exception? This change will require users to call "Init" for each registry instance which looks to me very cumbersome (especially right now it's not thread safe)

**Comment by bddppq** [comment]
@onnxbot retest this please

**Comment by bddppq** [comment]
@linkerzhang No #894 will make the code super hard to maintain (not to mention playing with macros is really not fun).
So errors in schema registration phase should rarely happens (for op schema it only happens when we accidentally declared duplicated schemas), and when error happens it's an undefined behavior in onnx. If we can not afford abort during this phase, how about let's just log to stderr and keep going?

**Comment by linkerzhang** [comment]
#894 could be discussed in-place in the PR.

@bddppq  having an init() function makes the order of doing initialization clearly, which was kind of discussed and agreed in #696 . logging the error and keep going is good for other apps except windows, I think :), although I agree with you that rare error cases actually, just in case there's one.

**Comment by bddppq** [comment]
Another choice would be having separate registries for onnx core schemas and user defined schemas, this can hugely improve the guarantee of no duplications.

**Comment by linkerzhang** [comment]
@shschaefer may share more thoughts on having a deterministic order of initialization please. Thank you!

**Comment by linkerzhang** [comment]
btw, @bddppq  to have all the function proto cached, it's also good to have an init function :). Otherwise, the initialzation logic will be put in the getter covered by a "if" statement, which is not good.

**Comment by bddppq** [comment]
@linkerzhang Well FunctionProto instantiation can be done the same way as op schema registration, in that case there will no need of caching or Init. Adding Init is because the users code will end up doing onnx::init everywhere it imports onnx. And as I have mentioned above, this is an api breaking change, all existing onnx integrations need to be updated to insert the init call.
If you really insist to make the schema's initialization order predictable, we can archive it by putting the schemas' source of truth into yaml files and then write a script to generate one single .cc file that has the c++ part of all the op schemas in desired order, the instantiation order of static variables in one single compilation unit is deterministic.

**Pull request closed without merging**
