### PR TITLE
Update defs.cc

### PR DESCRIPTION
**Pull request by tjingrant**

### CODE REVIEW

**Comment by tjingrant** [comment]
I cannot build the latest master. I get the following error:
```
  Running setup.py develop for onnx
    Complete output from command /localhd/tjin/tensorflow_latest/bin/python2 -c "import setuptools, tokenize;__file__='/localhd/tjin/onnx_dev/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running create_version
    running egg_info
    writing requirements to onnx.egg-info/requires.txt
    writing onnx.egg-info/PKG-INFO
    writing top-level names to onnx.egg-info/top_level.txt
    writing dependency_links to onnx.egg-info/dependency_links.txt
    reading manifest file 'onnx.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*' under directory 'third_party'
    writing manifest file 'onnx.egg-info/SOURCES.txt'
    running build_ext
    running build_proto
    running build_proto_in
    compiling onnx.proto.in
    compiling /localhd/tjin/onnx_dev/onnx/onnx/onnx-ml.proto
    building 'onnx.onnx_cpp2py_export' extension
    powerpc64le-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/localhd/tjin/onnx_dev/onnx -I/localhd/tjin/onnx_dev/onnx/third_party/pybind11/include -I/usr/include/python2.7 -I/usr/include/python2.7 -c /localhd/tjin/onnx_dev/onnx/onnx/onnx-ml.pb.cc -o build/temp.linux-ppc64le-2.7/localhd/tjin/onnx_dev/onnx/onnx/onnx-ml.pb.o -std=c++11
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    powerpc64le-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/localhd/tjin/onnx_dev/onnx -I/localhd/tjin/onnx_dev/onnx/third_party/pybind11/include -I/usr/include/python2.7 -I/usr/include/python2.7 -c /localhd/tjin/onnx_dev/onnx/onnx/cpp2py_export.cc -o build/temp.linux-ppc64le-2.7/localhd/tjin/onnx_dev/onnx/onnx/cpp2py_export.o -std=c++11
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    /localhd/tjin/onnx_dev/onnx/onnx/cpp2py_export.cc:1:31: fatal error: pybind11/pybind11.h: No such file or directory
    compilation terminated.
    error: command 'powerpc64le-linux-gnu-gcc' failed with exit status 1
```

Any idea what's going on?

**Comment by bddppq** [comment]
`pybind11/pybind11.h: No such file or directory`
Looks like the submodules are not fetched in your working copy. Please do 'git submodule update --init --recursive'

**Comment by bddppq** [comment]
There is another PR doing this change already: https://github.com/onnx/onnx/pull/127/files/e43f2825951834a0197053788cccd90e8e87fdbb#diff-baadf6fd14a4a80f0fe30bb743d33357L101

**Comment by tjingrant** [comment]
Great! It installs now. Looking forward to its merging!

**Pull request closed without merging**
