### PR TITLE
Revert MeanSquaredDistance(12)

### PR DESCRIPTION
**Pull request by codemzs**
This change reverts MeanSquaredDistance(12) spec (below commit) because it is not fully verified to work as it should.

#2570

Unfortunately, this spec was one among the few specs that was checked in a rush between 02/2020 and 03/2020. Its presence has jeopardized ONNX 1.7 release but removing it will give us appropriate confidence level in the quality for ONNX 1.7 release.

### CODE REVIEW

**Comment by codemzs** [comment]
@houseroad is merge from master enough, do we not have to regenerate the MD files?

**Comment by KsenijaS** [comment]
looks good.

**Comment by codemzs** [comment]
@houseroad It seems Caffe2 tests are [failing ](https://circleci.com/gh/onnx/onnx/4654?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)to build with the below error:

ninja: error: build.ninja:40966: multiple rules generate ../tools/build_variables.bzl [-w dupbuild=err]

Any idea what happened with PyTorch?

**Comment by codemzs** [comment]
@houseroad I already have.

**Comment by houseroad** [comment]
license/cla Expected — Waiting for status to be reported?

Why?

**Comment by codemzs** [comment]
@houseroad I will appreciate if you please merge https://github.com/pytorch/pytorch/pull/37309 ... I can take care of the rest

**Pull request merged**
