### PR TITLE
Moved elem_type_ (previously TensorProto_DataType) to registry pattern

### PR DESCRIPTION
**Pull request by bwasti**
Utilize protobufs reflection to make the element type system generic in the Graph representation

### CODE REVIEW

**Comment by houseroad** [comment]
@onnxbot add to whitelist

**Comment by linkerzhang** [comment]
Sorry that I probably missed sth, by looking thru the PR, I don't get the point of introducing the new type wrapper.

**Comment by houseroad** [comment]
I think this purpose of this PR is to decouple the TensorProto.EleType from the IR, so IR will be more flexible. Users can register their own element type.

**Comment by linkerzhang** [comment]
@houseroad Thank you very much for following up! I don't quite understand. How can they be decoupled please? TensorProto.DataType contains all types supported. There's no way for us to extend more types without touching this. Correct me if I'm wrong please.

**Comment by bwasti** [comment]
holding off on attempting to merge this for now

**Pull request closed without merging**
