### PR TITLE
MacOS release action is failing.

### PR DESCRIPTION
**Pull request by liqunfu**
### Description

(https://github.com/actions/setup-python/issues/855)

### CODE REVIEW

**Comment by cjvolzka** [comment]
@liqunfu would I be correct in guessing I'd also need to pull this into 1.16.1 (after it merges into main) to resolve the MacRelease check issues I'm seeing in https://github.com/onnx/onnx/pull/6108?

**Comment by justinchuby** [comment]
Does the change fix the error?

**Comment by liqunfu** [comment]
> @liqunfu would I be correct in guessing I'd also need to pull this into 1.16.1 (after it merges into main) to resolve the MacRelease check issues I'm seeing in #6108?

This 

> @liqunfu would I be correct in guessing I'd also need to pull this into 1.16.1 (after it merges into main) to resolve the MacRelease check issues I'm seeing in #6108?

We need the fix in order to build wheels to be published. Unless there is already wheels built, tested, and ready to upload to pypi, we need fix the issue this PR is targeting. Hopefully github team can the issue without this PR: https://github.com/actions/setup-python/issues/855.

**Comment by liqunfu** [comment]
> Does the change fix the error?

no. the issue is with setup python: https://github.com/actions/setup-python/issues/855. We need to first wait to see if github team has a solution to the original issue. We will then see if a PR is needed with the solution.

**Comment by mayeut** [comment]
> We need to first wait to see if github team has a solution to the original issue. We will then see if a PR is needed with the solution.

I wouldn't hold my breath on a solution in the short term given at least Python 3.8 & 3.9 are built from sources with homebrew dependencies on macOS x86_64.

My 2 cents, either:
- use `macos-12` instead of `macos-latest`: it was the previous latest when the workflow was last successful and is x86_64
- change `host-architecture` from `x64` to `arm64`: the architecture of the runner changed when moving from `macos-12` to `macos-14`, it shall probably be reflected here.

The first one comes with no risk in the short term (moving away from macOS-12 will need to happen at some point).
The second one will probably unveil other failures later in the workflow that will require more fixes.

**Comment by justinchuby** [comment]
Is it possible to create x64 universal builds from arm64?

**Comment by mayeut** [comment]
> Is it possible to create x64 universal builds from arm64?

Yes, it's possible to create universal2 builds from macOS arm64.
Not only the build is possible but we can also test x86_64 on macOS arm64 thanks to Rosetta 2 translation.

I opened #6117

**Pull request closed without merging**
