### PR TITLE
update readme install command to fix issue 1302

### PR DESCRIPTION
**Pull request by maxwillzq**
see https://github.com/onnx/onnx/issues/1302

### CODE REVIEW

**Comment by maxwillzq** [comment]
@houseroad ,

Thanks a lot for your comments.  Could you help take a look at issue #1302 while install does not work to when load defs in python?

**Comment by maxwillzq** [comment]
After clean build, it have no problem. Thanks a lot

**Comment by houseroad** [comment]
@maxwillzq since the problem is solved, can we close the PR?

**Comment by maxwillzq** [comment]
Yes, we can

**Pull request closed without merging**
