### PR TITLE
Add support for default attributes within FunctionExpandHelper

### PR DESCRIPTION
**Pull request by Ewa21**
If a `Function` node is missing a required attribute, the `FunctionExpandHelper` doesn’t look for the default value of the attribute in the operator schema.

In effect nodes in the expanded subgraph do no have attributes with those default values.

The main purpose of this PR is to add default attributes into nodes in subgraph created by `FunctionExpandHelper`. The attributes are gathered from the operator’s schema.

### CODE REVIEW

**Comment by Ewa21** [comment]
If a Function node is missing a required attribute, the FunctionExpandHelper doesn’t look for the default values of the attribute in the operator schema.

In effect nodes in the expanded subgraph do no have attributes with those default values.

The main purpose of this PR is to add default attributes into nodes in subgraph created by `FunctionExpandHelper`. The attributes are gathered from the operator’s schema.

**Comment by postrational** [comment]
We found this issue when adding support for `MeanVarianceNormalization` using an ONNX function. I think this fills in a gap in the `FunctionExpandHelper`.

**Comment by linkerzhang** [comment]
@Ewa21 please sign the CLA.

**Comment by Ewa21** [comment]
> @Ewa21 please sign the CLA.

Done :)

**Comment by linkerzhang** [comment]
the branch is out of date with the base branch. @Ewa21 please sync master and update this branch.

**Comment by Ewa21** [comment]
> the branch is out of date with the base branch. @Ewa21 please sync master and update this branch.

Done :)

**Comment by gramalingam** [comment]
Hmm, seems to have become out-of-date again! Normally, there is an option to "update branch" in the UI right here, but it seems to be missing here ... not sure why.

**Comment by linkerzhang** [comment]
yep. interesting. The "update the branch" button is not shown in this PR. @Ewa21 you'll have to update the branch by yourself again.

**Pull request merged**
