### PR TITLE
Replace "master" references to "main"

### PR DESCRIPTION
**Pull request by weonyuan**
* Apply changes to repos that have since renamed their "master" branch to "main"
* Fix some broken URLs. Point broken caffe2 links to pytorch where it caffe2 is now stored

Signed-off-by: Weon Yuan wwyuan@us.ibm.com

### CODE REVIEW

**Review by gramalingam — APPROVED** [review]
LGTM, thanks!

**Review by jcwchen — APPROVED** [review]
Thank you for replacing them! Please sign-off your commit (and force-push).

**Comment by weonyuan** [comment]
Thank you for reviewing! I had to resolve a merge conflict and sign off from it. Can someone help me push this? I do not have write access to the repo...

**Review by jcwchen — APPROVED** [review]
> Thank you for reviewing! I had to resolve a merge conflict and sign off from it. Can someone help me push this? I do not have write access to the repo...

Actually the DCO fails and therefore it cannot be merged. I would suggest you softly git reset to the base commit, git add the modified files in this PR and git commit with `--signoff` again. It should resolve the DCO failure. Then I would help you to merge this PR. Thank you for your time!

**Comment by weonyuan** [comment]
Hi @jcwchen I tried to follow your steps by performing a soft git reset to a commit prior to my initial commit, followed with git add to the modified files in this PR, and finally git commit with --signoff. Not sure why I am failing DCO. Sorry, this is my first PR for onnx

**Review by xadupre — APPROVED** [review]

**Comment by jcwchen** [comment]
> Hi @jcwchen I tried to follow your steps by performing a soft git reset to a commit prior to my initial commit, followed with git add to the modified files in this PR, and finally git commit with --signoff. Not sure why I am failing DCO. Sorry, this is my first PR for onnx

No worries. I am here to help.
https://github.com/onnx/onnx/pull/4864/commits/58698cb722ac6d3de20db47b9b4692b07ee99296 this is the old commit that which is not signoffed. So I would suggest you softly git reset to the previous commit of this one, signoff again and git push -f. Or, perhaps simply create another new PR with the same update and git commit `--signoff`. It's up to you. Thank you for your time!

**Comment by weonyuan** [comment]
Okay I figured it out. Turns out I needed to do a lot of setup - generating a SSH key, generating a GPG key, figuring out the difference between SSH and GPG, and telling GitHub to recognize them. Nonetheless, I was able to follow your instructions again @jcwchen and sign off my commit properly. Thanks again!

**Comment by jcwchen** [comment]
Thank you for resolving it! Appreciate it. Merged.

**Pull request merged**
