### PR TITLE
Fix: skip empty input output names in Extractor

### PR DESCRIPTION
**Pull request by wine99**
### Description
In the extractor, when building the mapping from output names to node index, skip empty outputs. When searching reachable nodes, skip empty inputs.

### Motivation and Context

image

image

For example, in the LLMs (e.g. Llama3) onnx model generated by onnxruntime-genai, there are nodes with optional inputs and outputs which are not used. Extracting a subgraph including these nodes will have an incorrect result.

### CODE REVIEW

**Review by gramalingam — APPROVED** [review]

**Comment by wine99** [comment]
@gramalingam How can I start the CI checks?

**Comment by gramalingam** [comment]
> @gramalingam How can I start the CI checks?

Started it.

**Review by wine99 — COMMENTED** [review]
Fixed style issues

**Comment by wine99** [comment]
@gramalingam Could you help update branch and start the CI again?

**Pull request merged**
