### PR TITLE
[WIP] Introducing Some Operators Required by Object Detection Models

### PR DESCRIPTION
**Pull request by houseroad**
Still in progress, only RoIAlign's definition is ready for review; other parts are still under development.

Operator definitions:
- [ ] BBoxTransform
- [ ] BoxWithNMSLimit
- [ ] GenerateProposals
- [x] RoIAlign

Node tests:
- [ ] BBoxTransform
- [ ] BoxWithNMSLimit
- [ ] GenerateProposals
- [ ] RoIAlign

### CODE REVIEW

**Comment by wschin** [comment]
For those very specific operators, in addition to high-level descriptions, users may also need mathematical documentation for implementing them. Otherwise, it might lead to some reverse engineering and hard to sync with all partners.

**Comment by houseroad** [comment]
@wschin yeah, I will add more description, and make sure people can understand the logic behind.

**Comment by Maratyszcza** [comment]
@houseroad Would be great to use this opportunity to find better names for operators.

**Comment by houseroad** [comment]
@Maratyszcza i am totally open to it. Let's have some offline discussion next week :-)

**Comment by houseroad** [comment]
Some design decision needs to be made here. I think RoIAlign is fine. For the other three, we probably need to reconsider how to define the API.

**Comment by houseroad** [comment]
@linkerzhang if you guys want to propose other design, feel free to create new PR(s). I can just drop this one.

**Comment by zhangxiang1993** [comment]
Is this PR still in Progress? Thanks! @houseroad

**Comment by daquexian** [comment]
@houseroad What's the current states of detection ops? :) Is there something I can help with (like tests)?

**Comment by houseroad** [comment]
@daquexian thanks for offering help. I think RoIAlign is good to go. Could you create a separate PR for it and adding some tests for RoIAlign? Other ops, not sure they are general enough to be pushed into ONNX spec, since most of frameworks don't have those ops.

**Comment by Maratyszcza** [comment]
These operators bear a lot of legacy issues. In particular, storing batch index in a float tensor is a 100% bad idea. There are refactored versions of Mask R-CNN ops in pytorch/pytorch#15889, they would be a better starting point for ONNX standartization.

**Comment by houseroad** [comment]
@daquexian before working on RoIAlign, checking @Maratyszcza's proposal should be a good idea. :-)

**Comment by daquexian** [comment]
@houseroad Hi, sorry for the delay :) I have read @Maratyszcza's implementation. Does it mean it is better to add a separate `batch_split` input to `RoIAlign`, instead of storing `batch_id` in `rois`?

**Comment by prasanthpul** [comment]
@houseroad should this be closed since there are now PRs for the individual ops?

**Pull request closed without merging**
