### PR TITLE
[Minor need to be in 1.5]Fix an issue in NMS test data which introduce wrong shape.

### PR DESCRIPTION
**Pull request by HectorSVC**
1. Fix an issue in NMS test data which introduce wrong shape.
2. Add node test data for NMS

### CODE REVIEW

**Comment by ebarsoum** [comment]
Can you fix the failing check.

**Comment by HectorSVC** [comment]
what happened to travis-ci? half done succeed. another half always waiting?

**Comment by HectorSVC** [comment]
could someone help merge it?

**Comment by HectorSVC** [comment]
Build timeout?

**Comment by linkerzhang** [comment]
re-triggered the one pipeline failed. will merge this once all CI passes.

**Pull request merged**
