### PR TITLE
Tiny fix to the description of the Abs operator

### PR DESCRIPTION
**Pull request by ShayHacohen**
Previous description seemed like a typo; this commit is a suggested improvement to it

### Description
Just a tiny phrasing modification to the description of the Abs operator.

### Motivation and Context
The current description seems to contain a typo. Not a huge deal but I figured I might as well propose what I hope is a reasonable correction.

### CODE REVIEW

**Comment by yuanyao-nv** [comment]
Thanks for catching this. You would need to modify the definition in `defs.cc` and rerun `generate_doc.sh` to correctly modify `Operators.md`.

**Comment by xadupre** [comment]
you need to run `ONNX_ML=0 python onnx/defs/gen_doc.py` and add the changes it produces to the PR.

**Comment by ShayHacohen** [comment]
Thanks a lot for the instructions, @yuanyao-nv and @xadupre!
I ran the script as stated and committed the resulting changes (which consisted of modifications to docs/Changelog.md and docs/Operators.md).

Does this look alright?

**Comment by ShayHacohen** [comment]
As a small update: I noticed that I forgot to sign off the commit and trying to amend it led to all sorts of weird shenanigans, so I figured the path of least resistance would be to just make a new, neater PR that contains the changes described here. It is this one:
https://github.com/onnx/onnx/pull/5136

**Pull request closed without merging**
