### PR TITLE
Update requirements.txt (#4223)

### PR DESCRIPTION
**Pull request by etiotto**
* Upgrade python syntax with pyupgrade (#4212)

Signed-off-by: Eduardo <eduardomoreno2594@gmail.com>

* Update requirements.txt

Signed-off-by: Eduardo <eduardomoreno2594@gmail.com>

* include the previous restriction as well

Signed-off-by: Eduardo <eduardomoreno2594@gmail.com>

Co-authored-by: Justin Chu <justinchuby@users.noreply.github.com>

**Description**
- Describe your changes.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Review by jcwchen — APPROVED** [review]

**Comment by garymm** [comment]
@jcwchen can you please merge this? It's blocking integration testing with ORT.

**Comment by jcwchen** [comment]
license/cla is still not removed entirely... I will try to make it pass

**Comment by jcwchen** [comment]
Try to reopen to this PR for removing unnecessary CLA

**Comment by jcwchen** [comment]
CLA assistant should be removed completely, but somehow it didn't... I will work with @prasanthpul to solve this issue. For now, to quickly unblock this urgent PR, @etiotto could you please sign-off CLA if possible? Thank you.

**Pull request merged**
