### PR TITLE
op signature consistency - weight input name

### PR DESCRIPTION
**Pull request by prasanthpul**
Any variable that represents a weight tensor will utilize the name “W”

### CODE REVIEW

**Comment by bddppq** [comment]
hmm, using "bias" for bias and then "W" for weights sounds inconsistent to me

**Comment by prasanthpul** [comment]
I'd be okay changing 'bias' to 'B' in a separate PR

**Comment by ezyang** [comment]
If we have a philosophy like this, it is worth documenting somewhere. Maybe add a PHILOSOPHY.md

**Comment by prasanthpul** [comment]
fyi - there is a separate pr for bias (#269) and another pr for OpConventions (#270)

**Pull request merged**
