### PR TITLE
Add maxpool test cases

### PR DESCRIPTION
**Pull request by fumihwh**

### CODE REVIEW

**Comment by houseroad** [comment]
@onnxbot test this please

**Comment by fumihwh** [comment]
@houseroad 
About oop and reusing function same in `averagepool.py` and `maxpool.py`,
I have no idea where should I put them (`_get_pad_shape`, `_get_output_shape`, `_pool`) into.
Should I put them into `utils.py`? or a new file? I am not sure.
Any advice?

**Comment by fumihwh** [comment]
@houseroad I've updated this pr.

**Comment by houseroad** [comment]
@onnxbot retest this please

**Comment by houseroad** [comment]
@fumihwh all looks good. Nit: we should also mention that the max value does not consider the pad.

**Pull request merged**
