### PR TITLE
Fix comma in Gemm description

### PR DESCRIPTION
**Pull request by lutzroeder**

### CODE REVIEW

**Comment by houseroad** [comment]
I think I already fix this in https://github.com/onnx/onnx/pull/907 :-)

**Comment by lutzroeder** [comment]
@houseroad This is fixed in `Gemm` v7 but the older versions still have the comma on the wrong line.

**Comment by houseroad** [comment]
@lutzroeder yes, you are right, I forgot to fix the problem in the old.cc.

Could you create another PR to solve it?

Thanks!

**Comment by lutzroeder** [comment]
@houseroad #1035

**Pull request closed without merging**
