### PR TITLE
switch instructions to conda-forge onnx

### PR DESCRIPTION
**Pull request by dougalsutherland**
Maybe "nicer" than @ezyang's personal channel, now that [it's available](https://github.com/conda-forge/onnx-feedstock).

### CODE REVIEW

**Comment by Shannshan47** [comment]
I don't know anything about this site. Don't know nothing about github. I thought signing up it would automatically fix problem. Is there any other simple way to help me. If not thanks and God Bless

**Comment by prasanthpul** [comment]
Is the conda-forge version updated automatically? Does it always reflect the latest master version or a specific branch?

**Comment by dougalsutherland** [comment]
It's not updated automatically, it needs someone to go send a (very easy) PR to [the feedstock](https://github.com/conda-forge/onnx-feedstock/). Assuming no dependency changes, all it needs is an update to the `version` and `sha256` lines in [`meta.yaml`](https://github.com/conda-forge/onnx-feedstock/blob/master/recipe/meta.yaml).

@ezyang and I can both merge these PRs; if you want anyone else to be able to, just send a PR adding their github id to the bottom of `meta.yaml` and then they'll get merge privileges too.

**Comment by ezyang** [comment]
It's far far easier to get the conda-forge package updated; it's no longer me (black box) popping out a binary when we release.

**Comment by prasanthpul** [comment]
Perfect. Let's make it a part of our standard release process.

**Pull request merged**
