### PR TITLE
Add integer support to Clip

### LINKED ISSUE #2450: Clip support for integer tensors
[Clip](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Clip) inputs in constrained to floating points. I have tensors that are indices, and thus `int64` and would like to `Clip` them to valid ranges.
In general, what is the rationale for limiting operators input types? does it really affect binary sizes?

### PR DESCRIPTION
**Pull request by TMVector**
Expand Clip operator to support integer types too. Fixes #2450 and is the first step in #2528.

## Tests
It looks like tests are to be self-contained for inclusion in the docs, but it also looks like data type support is not well tested in general, and adding one for each type would be verbose and noisy. I have modified the `clip_default` node test to loop over the supported dtypes and generate the same test case for each one (the constants are all unsigned and small in that test). That increases the number of tests generated from `clip_default` from 3 to 33. **Feedback would be appreciated.** If we want to expand dtype tests for other operators then it might be worth thinking about how to do that without making all the doc examples noisy.

## ~This PR is not ready to merge -- backend test data needs generating. [help wanted]~
~When I ran `tools/update_doc.sh` all of the `test/data/` ONNX files had small changes in -- do I need a specific version of protobuf or something? I'm using protobuf 3.11.2 installed with conda.~ Turns out it was from the ir/opset version being updated.

### CODE REVIEW

**Comment by linkerzhang** [comment]
please fix ci failure - "
+flake8
2326
./onnx/backend/test/case/node/clip.py:68:24: E222 multiple spaces after operator"

**Comment by TMVector** [comment]
Okay, I actually ran some diffs on the text form of the protobufs, and it turns out the differences are all from ir/opset version updates. I will take it that means it's okay to only update tests actually changed by this PR.

What is the convention with regard to backend tests -- just overwrite the tests for old ir/opset versions?

Is it okay to change the test to loop over dtypes like I have? (I'm thinking of the docs mainly).

@linkerzhang feedback on testing and above questions would be really helpful :)

**Comment by TMVector** [comment]
Looks like circleci failing is due to ORT not producing Python 2.7 builds anymore

**Comment by TMVector** [comment]
And the failures now look to be nbval/nbformat related

**Comment by askhade** [comment]
Looks like you are adding a new test for every combination of test case + data type. For example 
test_clip_default_inbounds_float32
test_clip_default_inbounds_int32
test_clip_default_max_float32
test_clip_default_max_int32

This is adding too many files which in my opinion are unnecessary... I would suggest you to pick a few out of these.... I do not believe we need a test case for each and every data type

**Comment by TMVector** [comment]
There is now only one additional test (clip_default_int8) which adds 3 test files.

I would love to see a full backend test suite which tested support for data types, but I guess that's outside the scope of this PR anyway.

**Comment by linkerzhang** [comment]
@TMVector can you fix the conflicts so that the PR can be merged?

**Comment by linkerzhang** [comment]
merging #2608 introduces new conflicts .....

@TMVector  can you update it again?

**Pull request merged**
