### PR TITLE
Clarify CONTRIBUTING.md documentation generation steps

### PR DESCRIPTION
**Pull request by fdwr**
Let's make this clearer so people don't waste an hour (like me 😅) wondering why running the script yields no changes to Operators.md. For some reason, the much more rarely updated Operators-ml.md is the default update target when `ONNX_ML` is not defined, rather than the one everyone typically wants to update. 🙃 Also, explicitly relist the install step rather than referring back to an earlier step which is actually executed from a different directory (which confuses things).

FYI @jcwchen

### CODE REVIEW

**Review by jcwchen — APPROVED** [review]
LGTM. @fdwr Thank you for the improvement!

**Comment by fdwr** [comment]
@jcwchen : Welcome. Do editorial changes need review from a specific sig reviewer, or anyone? I'd propose also that `python onnx/defs/gen_doc.py` just take an *explicit* parameter, rather than using a wonky environment variable `ONNX_ML`, but I'm unsure who to propose that idea too.

**Comment by jcwchen** [comment]
> @jcwchen : Welcome. Do editorial changes need review from a specific sig reviewer, or anyone? I'd propose also that `python onnx/defs/gen_doc.py` just take an _explicit_ parameter, rather than using a wonky environment variable `ONNX_ML`, but I'm unsure who to propose that idea too.

Since it is related to infra, you can propose it to @onnx/sig-archinfra-approvers . Thanks

**Review by askhade — APPROVED** [review]

**Comment by askhade** [comment]
> @jcwchen : Welcome. Do editorial changes need review from a specific sig reviewer, or anyone? I'd propose also that `python onnx/defs/gen_doc.py` just take an _explicit_ parameter, rather than using a wonky environment variable `ONNX_ML`, but I'm unsure who to propose that idea too.

you can create a PR and add arch infra sig

**Pull request merged**
