### PR TITLE
Define slice behavior for start or end larger than the number of elements

### PR DESCRIPTION
**Pull request by smessmer**

### CODE REVIEW

**Comment by bddppq** [comment]
Looks good to me. python and numpy behaves this way and I would like to follow the same semantic.

**Comment by dzhulgakov** [comment]
So, the desired behavior for (cut to the end) is INT_MAX, right? If so - shall we clarify it directly in the op description that it's what recommended? It might be useful in some backends to directly identify that the output is taken till the end. (I don't like INT_MAX but I don't see a better option)

**Comment by houseroad** [comment]
@dzhulgakov We try to follow python/numpy style. Since the size can be arbitrary, it is safe to use INT_MAX. Although, any number larger than the size should work.

**Comment by bddppq** [comment]
ping @linkerzhang for review

**Comment by dzhulgakov** [comment]
I'm totally on board with it. What I'm saying - just add a comment in description that if you want to take towards the very end - using INT_MAX is fine.

**Pull request merged**
