### PR TITLE
Turn enum DifferentiationCategory to enum class DifferentiationCategory

### PR DESCRIPTION
**Pull request by cyyever**
### Motivation and Context
For better type checking.

### CODE REVIEW

**Comment by justinchuby** [comment]
Will this break external usage?

**Comment by cyyever** [comment]
> Will this break external usage?

Not sure.

**Review by justinchuby — CHANGES_REQUESTED** [review]
I think this change is risky since the enum is public

**Comment by cyyever** [comment]
> I think this change is risky since the enum is public

I agree, so now I mark it as WIP

**Comment by xadupre** [comment]
I agree your change makes it better but it is going to break every package linking with onnx (that includes onnxruntime). I suggest keeping the code as it is.

**Pull request closed without merging**
