### PR TITLE
Added Windows ARM64 build support for ONNX

### PR DESCRIPTION
**Pull request by ilya-lavrenov**

### CODE REVIEW

**Review by jcwchen — COMMENTED** [review]
Thank you for the contribution! I don't have a Windows ARM64 machine to test this -- @ilya-lavrenov do you have such an environment to test/verify this PR?

**Comment by ilya-lavrenov** [comment]
> Thank you for the contribution! I don't have a Windows ARM64 machine to test this -- @ilya-lavrenov do you have such an environment to test/verify this PR?

Yes, what kind of tests can I run to check correctness?

BTW, if you have macOS with M1 / M2, you install Windows ARM64 using Parallels Desktop and check everything there.

**Comment by jcwchen** [comment]
> Yes, what kind of tests can I run to check correctness?

Thanks for the info (I don't have a M1/M2 machine either tho). Something like running `pytest` under onnx repo
```
git clone https://github.com/onnx/onnx.git
cd onnx
pip install -e . # build ONNX from source in your Windows arm64 machine with this PR.
pytest
```

**Comment by justinchuby** [comment]
I think we can revert if anything goes wrong

**Review by justinchuby — APPROVED** [review]

**Pull request merged**
