### PR TITLE
Fix pow op's test case (#546)

### PR DESCRIPTION
**Pull request by fumihwh**
Just change shape of `y` from `(3,)` to `(2,)` to fit the broadcast rule and expected value `z` also.

### CODE REVIEW

**Comment by houseroad** [comment]
@fumihwh Thanks for the contribution. You should also gen_doc.py to update the md files.

**Comment by fumihwh** [comment]
@houseroad Sorry for the connivence. I will add a commit for doc updating.

**Comment by houseroad** [comment]
No worries, also backend test data should be updated. :-)

**Comment by bddppq** [comment]
@onnxbot test this please

**Pull request merged**
