### PR TITLE
Fix protobuf version unmatch 

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Comment by cyyever** [comment]
@justinchuby Is it reasonable?

**Comment by justinchuby** [comment]
I don’t feel strongly but I don’t think this is needed. Keeping Ubuntu latest means we don’t have to update this file every time a new version comes out

**Comment by cyyever** [comment]
@justinchuby I felt strange that 'ubuntu-latest' points to 22.04..

**Comment by cyyever** [comment]
@justinchuby  This PR may solve the current protobuf issue.

**Comment by justinchuby** [comment]
Thanks!

**Review by justinchuby — APPROVED** [review]

**Comment by justinchuby** [comment]
Still failing it seems

**Comment by cyyever** [comment]
> Still failing it seems

Still working on it, wait

**Pull request merged**
