### PR TITLE
Fix weekly-CI failure: correct protobuf installation and skip list

### PR DESCRIPTION
**Pull request by jcwchen**
**Description**
- To fix protobuf.rb not found, directly build protobuf 3.11.3 from source, just like what other CIs do
- Switch caffenet-3 and caffenet-6 in skip list due to the bug fix: https://github.com/onnx/models/pull/388

**Motivation and Context**
Weekly-CI has failed for a while

### CODE REVIEW

**Comment by askhade** [comment]
is this the one used to publish weekly packages to test pypi?

**Comment by jcwchen** [comment]
> is this the one used to publish weekly packages to test pypi?

No, this is the one for checking (onnx.checker) all models from ONNX Model Zoo. The one for testpypi works normally. Thanks

**Comment by askhade** [comment]
Can you trigger the failing CI itself for this PR

**Comment by jcwchen** [comment]
> Can you trigger the failing CI itself for this PR

Since we can only manually trigger the CIs from the repo's branch, I can only trigger it in my forked repo: https://github.com/jcwchen/onnx/actions/runs/936466270...

**Review by askhade — APPROVED** [review]

**Pull request merged**
