### PR TITLE
replace whitelist by safelist

### PR DESCRIPTION
**Pull request by AlexandreEichenberger**
Signed-off-by: Alexandre Eichenberger <alexe@us.ibm.com>

**Description**
Change whitelist into the more neutral safelist word 

**Motivation and Context**
We have been asked to remove certain terms from our code, this is the only instance that I found in the entire ONNX/ONNX repo.

No functionality was changed, just the name of a function.

### CODE REVIEW

**Review by askhade — APPROVED** [review]
Thanks!

**Comment by askhade** [comment]
Although the PR is merged it would be nice if you created an issue and linked this PR. It will be easier for tracking. We should ideally have issues for all such tasks - changing names to more neutral names, changing master -> main and may be more.

**Comment by AlexandreEichenberger** [comment]
@askhade I don't understand your request: you prefer that there is one issue for each PR (happy to add one), or that there is one issue to represent all of the changes for neutral names PRs? Thanks for clarifying

**Comment by askhade** [comment]
Either way works - I just want a way to track these work items, so that we can easily gather all the work that was done towards making code\branch names etc neutral.

**Pull request merged**
