### PR TITLE
change travis ci as onnx_ml=1 covers onnx_ml=0.

### PR DESCRIPTION
**Pull request by linkerzhang**
…educe the ci latency.

### CODE REVIEW

**Comment by linkerzhang** [comment]
it is covered, right?

**Comment by bddppq** [comment]
@linkerzhang 
> "the code should be always be built with ONNX_ML =0 once it could be built when ONNX_ML=1" 

Not really, we have spotted couple times in PRs that people forgot adding ifdefs to guard access to onnxml stuffs.

**Comment by wschin** [comment]
@bddppq , does it mean it's a good reason to add ONNX_ML=1 for test? Those situation can be avoided if we have tests.

**Comment by bddppq** [comment]
@wschin Sorry I don't quit follow your suggestion. Could you elaborate how is that going to help?

**Comment by wschin** [comment]
If one doesn't consider ONNX_ML in their PR, the unit test related that PR may throw so that the author can fix it before checking in the changes.

**Comment by bddppq** [comment]
@wschin code example of such tests?

**Comment by wschin** [comment]
That test makes sense! If we have ONNX_ML=0 and ONNX_ML=1, we need to test both of them. I have another question; couldn't everyone use ONNX_ML=1? We can still separate traditional ML ops from default onnx domain.

**Comment by bddppq** [comment]
Closing. We can revisit this if someday ONNX_ML={0,1} are unified.

**Pull request closed without merging**
