### PR TITLE
Fix backend test for ReferenceEvaluator with numpy 1.16.6

### PR DESCRIPTION
**Pull request by xadupre**
Replaces #4657.

### CODE REVIEW

**Comment by jcwchen** [comment]
Thank you for fixing this. Please allow me to reopen this PR to trigger release CIs.

**Review by jcwchen — COMMENTED** [review]
Tests with NumPy 1.16.6 now looks good, but tests in Windows x86 are still failing. (See https://github.com/onnx/onnx/actions/runs/3471448294/jobs/5800951391)

**Comment by xadupre** [comment]
Sorry for that, building onnx on Windows is always difficult. I'm working on that.

**Comment by xadupre** [comment]
The issues come from the use of int64 for integers. A couple of functions in x64 distribution don't support that.

**Comment by xadupre** [comment]
I added some code to catch the exceptions raised by numpy on python x86 to convert int64 into python int. It was working locally for me. I added an explicit comment that it was needed for x86 in the few places it was needed.

**Review by jcwchen — APPROVED** [review]
Overall looks good to me. Thank you for fixing them!

**Pull request merged**
