### PR TITLE
[Easy] Remove inappropriate const in version converter code

### PR DESCRIPTION
**Pull request by houseroad**
Address https://github.com/onnx/onnx/issues/1496

### CODE REVIEW

**Comment by houseroad** [comment]
cc @snnn

**Comment by snnn** [comment]
LGTM.

**Comment by Maratyszcza** [comment]
what is the point of removing `const`? `const` hints the reader that this variable never changes, and unless is breaks compilation / forces less efficient overload I don't see a good reason to remove it.

**Comment by houseroad** [comment]
For the function declaration, const int and int are the same thing, since they are passing value. Meanwhile, in the implementation, we almost never change the value of the parameters, and we would rather to make APIs consistent. In this diff, we also would like to remove the const of the return value, because we may have some post processing afterward.

**Comment by snnn** [comment]
Please make it consistent. Either you always write code like:
```
void func(int c);
```
or 

```
void func(const int c);
```
Most people will choose the first one. 
Most open source code bases don't have the second one.

**Pull request merged**
