### PR TITLE
Add Python 3.9 to release pipeline 

### PR DESCRIPTION
**Pull request by etusien**
Signed-off-by: Ewa21 <ewa.tusien@intel.com>

### CODE REVIEW

**Review by jcwchen — COMMENTED** [review]
Remove failing Python 3.5 and then release CIs should work. Thanks for picking this up!

**Comment by askhade** [comment]
Python 3.5 deprecation is checked in to master now... just merge with master should work

**Review by postrational — APPROVED** [review]

**Comment by postrational** [comment]
@askhade Should we merge this?

**Review by jcwchen — APPROVED** [review]
LGTM. Thanks

**Review by askhade — APPROVED** [review]

**Pull request merged**
