### PR TITLE
Another attempt to fix protobuf version problem

### PR DESCRIPTION
**Pull request by cyyever**
### Description

Another attempt to downgrade the protobuf version used in CI jobs

### CODE REVIEW

**Comment by cyyever** [comment]
@justinchuby Is it possible to run CD jobs before merge?

**Comment by cyyever** [comment]
@justinchuby Check it?

**Comment by justinchuby** [comment]
Thanks, looks like there isn’t a trigger for build page but this looks good to me

**Review by justinchuby — APPROVED** [review]

**Comment by cyyever** [comment]
@justinchuby Still doesn't work, we can use ubuntu24.04 for "Generate and publish ONNX docs" or try a lower pip protobuf?

**Comment by cyyever** [comment]
@justinchuby  Github action will points ubuntu-latest to 24.04 in these days, see 
```
https://github.com/actions/runner-images/issues/10636
```
we can wait it happen.

**Pull request merged**
