### PR TITLE
Clarify reduction op inputs can be rank-0 tensors (scalars)

### PR DESCRIPTION
**Pull request by gramalingam**
### Description
Clarify that the input of a reduction op can be a rank-0 tensor.

### Motivation and Context
There seems to be some confusion whether this is valid or not. The interpretation and return-value are straightforward with no ambiguity. So, clarify this explicitly.

### CODE REVIEW

**Review by jcwchen — APPROVED** [review]

**Comment by justinchuby** [comment]
@xiaowuhu @fatcat-z this means some functions we created don’t need to explicitly account for scalars

**Review by daquexian — APPROVED** [review]

**Comment by justinchuby** [comment]
Do we also have backend tests for this?

**Comment by xadupre** [comment]
Probably not otherwise the reference implementation would probably have failed those tests.

**Comment by justinchuby** [comment]
Should we clarify max and min as well? I found they also support scalars.

**Pull request merged**
