### PR TITLE
Update transpose doc

### PR DESCRIPTION
**Pull request by gramalingam**
### Description
Clarify the permutation specification of the Transpose op.

### Motivation and Context
It is not clear from the spec whether the i-th input axis corresponds to the perm[i]-th output axis or whether the i-th output axis corresponds to perm[i]-th input axis. Make this clear.

### CODE REVIEW

**Comment by justinchuby** [comment]
Would it be a good idea to address https://github.com/onnx/onnx/issues/4611 in the same PR?

**Comment by gramalingam** [comment]
> Would it be a good idea to address #4611 in the same PR?

Maybe. But at least some of those questions require some investigation ... it is easy enough to say 0D and 1D inputs _should_ be supported (the op is well-defined for these cases). But that doesn't mean that a specific implementation will support them ... only if we test it out, will we realize if some assumptions are being made.

**Comment by gramalingam** [comment]
Added point about perm being optional.

**Comment by gramalingam** [comment]
As for the question about 0D input tensors (scalars): it looks like both ONNX shape inference as well as its reference implementation need to be extended/fixed to handle this case.

**Review by xadupre — APPROVED** [review]

**Review by postrational — APPROVED** [review]

**Review by xadupre — APPROVED** [review]

**Comment by gramalingam** [comment]
I am a bit mystified how the test-data files got included in the changed files? Perhaps a result of merging with main branch? Still a bit confusing

**Comment by xadupre** [comment]
No clue. I don't remember seeing them when I reviewed the PR.

**Comment by gramalingam** [comment]
Looks like it might have come from the auto-update-doc ... though it was not designed to do so originally.

**Pull request closed without merging**
