### PR TITLE
Remove python 3.8 workflows (python 3.8 is eol)

### PR DESCRIPTION
**Pull request by cyyever**
### Description

Python 3.8 has reached End Of Life.

### CODE REVIEW

**Comment by andife** [comment]
https://github.com/onnx/onnx/issues/6298

**Comment by justinchuby** [comment]
PyTorch has dropped 3.8 for the up coming 2.6 release. That would be similar timing when we release 1.18 so I think that’s ok.

**Comment by andife** [comment]
The https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix and release https://github.com/pytorch/pytorch/blob/main/RELEASE.md#release-compatibility-matrix looks nice.

In my opinion we should have something like that publicly available.

From my experience with Onnx, a release every 4 months might be realistic?

**Comment by andife** [comment]
Now that pytorch and onnxruntime have discontinued support, I can well imagine removing 3.8. Now that we have added 3.13, this would also reduce CI runtimes.

@xadupre @gramalingam @justinchuby

**Review by andife — APPROVED** [review]

**Pull request merged**
