### PR TITLE
Add support for 16-bit quantization, in QuantizeLinear and DequantizeLinear

### PR DESCRIPTION
**Pull request by frank-ff**
**Description**
- Adds support for signed and unsigned 16-bit quantization in the QuantizeLinear and DequantizeLinear ops
- Generated new documentation via update_doc.sh script

**Motivation and Context**
- Today, ONNX only supports 8-bit quantization. 
- This change hopes to bring ONNX up to speed with the major NN frameworks and libraries that all support 16-bit.

### CODE REVIEW

**Comment by yufenglee** [comment]
Which are the major NN frameworks and libraries that you mentioned in the description? Do they get better performance?

**Comment by frank-ff** [comment]
Hi @yufenglee 

1. To answer your first question, here are some examples:

Tensorflow allows for arbitrary bit-width quantization (between 2 - 16 bits) : https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/fake-quant-with-min-max-args

TVM allows for 16-bit quantization as well, and in fact, is the default quantization width for certain op types: https://tvm.apache.org/docs/how_to/deploy_models/deploy_prequantized.html?highlight=16 (see the footnote that says "Without fast 8 bit instructions, TVM does quantized convolution in 16 bit")

CMSIS-NN has 16-bit operator support for most of its NN operators: https://www.keil.com/pack/doc/CMSIS/NN/html/group__groupNN.html


2. To answer your second question, yes, having higher granularity bitwidths in quantization helps increase accuracy at the cost of larger model sizes (but still better than full unquantized float32 models) -- this has been incredibly valuable in the models I've worked on personally. And in fact, scanning through the Issues list, it seems I'm not the only one: https://github.com/onnx/onnx/issues/3906

**Comment by frank-ff** [comment]
@gramalingam @yufenglee Any further comments or thoughts on this PR?

**Comment by sousoux** [comment]
Could I suggest that you add an extra levels attribute to the quantize and dequantize operator which matches the definition of levels in https://docs.openvino.ai/latest/openvino_docs_ops_quantization_FakeQuantize_1.html? It can default to the size of the container i.e. pow(2,8) for int8 and pow(2, 16) for int16. This would be very helpful for us.

**Comment by jywu-msft** [comment]
Can we revive this?

**Pull request closed without merging**
