### PR TITLE
Updated docs for DynamicQuantizeLinear to be consistent with reference implementation

### PR DESCRIPTION
**Pull request by Swopper050**
Hi! Something went wrong with my other pull request (#5601), so I forked the right version and tried again:

### Description

I changed the operator definition for DynamicQuantizeLinear to be consistent with the reference implementation as described in #5597

### Motivation and Context

#5597

### CODE REVIEW

**Comment by jcwchen** [comment]
Please allow me to reopen this PR for retriggering auto update doc CI.

**Review by jcwchen — COMMENTED** [review]
Thanks for the new PR and now the documents have been updated accordingly bi CIs. I will take care of Windows CI failure in another PR.

**Comment by Swopper050** [comment]
Awesome, thanks! Is there anything I can still do for this issue/PR?

**Review by jcwchen — APPROVED** [review]
I am good with this change, but it will need approval from @onnx/sig-operators-approvers. Could  @onnx/sig-operators-approvers please review this PR? Thanks.

**Review by xadupre — APPROVED** [review]

**Pull request merged**
