### PR TITLE
spelling pass for docs

### PR DESCRIPTION
**Pull request by brettkoonce**

### CODE REVIEW

**Comment by brettkoonce** [comment]
should this be forward, not foward?     https://github.com/onnx/onnx/blob/535c8c1ded151c772051dd8f7a0887752c2d4fd5/onnx/defs/rnn/defs.cc#L16

**Comment by houseroad** [comment]
Please fix the typos in def.cc files, then compile onnx project, and run gen_doc.py to update the docs.

**Comment by houseroad** [comment]
@brettkoonce yes, it should be forward.

**Comment by brettkoonce** [comment]
@houseroad Thanks for doing the update steps, my linux install is acting up!  Will get the workflow going before doing this next time!

**Comment by houseroad** [comment]
@brettkoonce No problem, thanks for your contribution. :-)

**Pull request merged**
