### PR TITLE
Update version number to 1.6.0

### PR DESCRIPTION
**Pull request by chinhuang007**
Update the version number file so the VERSION_NUMBER reflect the
latest release version number.

### CODE REVIEW

**Comment by wschin** [comment]
@kevinch-nv, please take a look. This PR is almost the same to your last PR to `rel-1.6.0` branch.

**Comment by prasanthpul** [comment]
I believe we generally do this by cherry picking that PR in its entirety from 1.6 branch into master, rather than making the changes separately.

**Comment by chinhuang007** [comment]
@wschin updated the doc

**Comment by wschin** [comment]
I agree with @prasanthpul. Could you cherry-pick it from `rel-1.6.0`? You can do
1. git checkout master
2. git cherry-pick 553df22
3. git commit -m "Cherry-pick 1.6.0 version number"
4. git push -f chinhuang007:update_version_number

**Comment by kevinch-nv** [comment]
Opened #2385 to handle the cherry-picking of the version back to master. Closing this PR.

**Pull request closed without merging**
