### PR TITLE
Switch from the current diff2html-ui.min.js to diff2html-ui-slim.min.js 

### PR DESCRIPTION
**Pull request by hamptonm1**
### Description

Switch from the current  diff2html-ui.min.js to diff2html-ui-slim.min.js 

### Motivation and Context

The orignal .js supports a larger number of languages than ONNX needs. Some of these languages specifically: coq, crmsh, and LSL -Linden Scripting Language pulls in terms that should be avoided. Since ONNX doesn't need these languages there's not a reason to include syntax highlighting support for them.
 
This will clean up the following Words Matter references:
 
```
{}{"Directory": ".","Query": "blacklist","Matches": "./onnx-mlir/third_party/onnx/docs/docsgen/source/static/diff2html-ui.min.js:1:!function(e,t){if(\"object\"==typeof exports&&\"object\"==typeof module)module.exports=t();else if(\"function\"==typeof define&&define.amd)define([],t);else{var n=t();for(var a in n)(\"object\"==typeof exports?exports:e)[a]=n[a](this,(()=>{return e={696:(e,t)=>{\"use strict\";Object.defineProperty(t,\"_esModule\",
{value:!0}
),t.convertChangesToDMP=function(e){for(var t,n,a=[],r=0;r<e.length;r++)n=(t=e[r]).added?1:t.removed?-1:0,a.push([n,t.value]);return a}},5826:(e,t)=>{\"use strict\";Object.defineProperty(t,\"__esModule\",
{value:!0}
),t.convertChangesToXML=function(e){for(var t=[],n=0;n<e.length;n++)
{var a=e[n];a.added?t.push(\"<ins>\"):a.removed&&t.push(\"<del>\"),t.push(a.value.replace(/&/g,\"&\").replace(/</g,\"<\").replace(/>/g,\">\").replace(/\"/g,\""\")),a.added?t.push(\"</ins>\"):a.removed&&t.push(\"</del>\")}
return t.join(\"\")}},6976:(e,t,n)=>{\"use strict\";var a;Object.defineProperty(t,\"__esModule\",
{value:!0}
),t.dif"{}}}},{}{"Directory": ".","Query": "whitelist","Matches": "./onnx-mlir/third_party/onnx/docs/docsgen/source/static/diff2html-ui.min.js:1:!function(e,t){if(\"object\"==typeof exports&&\"object\"==typeof module)module.exports=t();else if(\"function\"==typeof define&&define.amd)define([],t);else{var n=t();for(var a in n)(\"object\"==typeof exports?exports:e)[a]=n[a](this,(()=>{return e={696:(e,t)=>{\"use strict\";Object.defineProperty(t,\"_esModule\",
{value:!0}
),t.convertChangesToDMP=function(e){for(var t,n,a=[],r=0;r<e.length;r++)n=(t=e[r]).added?1:t.removed?-1:0,a.push([n,t.value]);return a}},5826:(e,t)=>{\"use strict\";Object.defineProperty(t,\"__esModule\",
{value:!0}
),t.convertChangesToXML=function(e){for(var t=[],n=0;n<e.length;n++)
{var a=e[n];a.added?t.push(\"<ins>\"):a.removed&&t.push(\"<del>\"),t.push(a.value.replace(/&/g,\"&\").replace(/</g,\"<\").replace(/>/g,\">\").replace(/\"/g,\""\")),a.added?t.push(\"</ins>\"):a.removed&&t.push(\"</del>\")}
return t.join(\"\")}},6976:(e,t,n)=>{\"use strict\";var a;Object.defineProperty(t,\"__esModule\",
{value:!0}
),t.dif"{}}}},{}{"Directory": ".","Query": "slave","Matches": "./onnx-mlir/third_party/onnx/docs/docsgen/source/static/diff2html-ui.min.js:1:!function(e,t){if(\"object\"==typeof exports&&\"object\"==typeof module)module.exports=t();else if(\"function\"==typeof define&&define.amd)define([],t);else{var n=t();for(var a in n)(\"object\"==typeof exports?exports:e)[a]=n[a](this,(()=>{return e={696:(e,t)=>{\"use strict\";Object.defineProperty(t,\"_esModule\",
{value:!0}
),t.convertChangesToDMP=function(e){for(var t,n,a=[],r=0;r<e.length;r++)n=(t=e[r]).added?1:t.removed?-1:0,a.push([n,t.value]);return a}},5826:(e,t)=>{\"use strict\";Object.defineProperty(t,\"__esModule\",
{value:!0}
),t.convertChangesToXML=function(e){for(var t=[],n=0;n<e.length;n++)
{var a=e[n];a.added?t.push(\"<ins>\"):a.removed&&t.push(\"<del>\"),t.push(a.value.replace(/&/g,\"&\").replace(/</g,\"<\").replace(/>/g,\">\").replace(/\"/g,\""\")),a.added?t.push(\"</ins>\"):a.removed&&t.push(\"</del>\")}
return t.join(\"\")}},6976:(e,t,n)=>{\"use strict\";var a;Object.defineProperty(t,\"__esModule\",
{value:!0}
),t.dif"{}}}},{}{"Directory": ".","Query": "master","Matches": "./onnx-mlir/third_party/onnx/docs/docsgen/source/static/diff2html-ui.min.js:1:!function(e,t){if(\"object\"==typeof exports&&\"object\"==typeof module)module.exports=t();else if(\"function\"==typeof define&&define.amd)define([],t);else{var n=t();for(var a in n)(\"object\"==typeof exports?exports:e)[a]=n[a](this,(()=>{return e={696:(e,t)=>{\"use strict\";Object.defineProperty(t,\"_esModule\",
{value:!0}
),t.convertChangesToDMP=function(e){for(var t,n,a=[],r=0;r<e.length;r++)n=(t=e[r]).added?1:t.removed?-1:0,a.push([n,t.value]);return a}},5826:(e,t)=>{\"use strict\";Object.defineProperty(t,\"__esModule\",
{value:!0}
),t.convertChangesToXML=function(e){for(var t=[],n=0;n<e.length;n++)
{var a=e[n];a.added?t.push(\"<ins>\"):a.removed&&t.push(\"<del>\"),t.push(a.value.replace(/&/g,\"&\").replace(/</g,\"<\").replace(/>/g,\">\").replace(/\"/g,\""\")),a.added?t.push(\"</ins>\"):a.removed&&t.push(\"</del>\")}
return t.join(\"\")}},6976:(e,t,n)=>{\"use strict\";var a;Object.defineProperty(t,\"__esModule\",
{value:!0}
),t.dif"{}}}},
 
```

### CODE REVIEW

**Comment by hamptonm1** [comment]
Hello @gramalingam!! I am new to the `onnx` community...... does the `enforce style` check usually take this long? Seems as if it is lagging. I wanted to get this simple fix reviewed and merged into `main`.

**Comment by jcwchen** [comment]
> Hello @gramalingam and @jcwchen!! I am new to the onnx community...... does the enforce style check usually take this long? Seems as if it is lagging. I wanted to get this simple fix reviewed and merged into main.

Hi @hamptonm1,

Thanks for contribution. It shouldn't, but I am seeing the lag happens globally. It seems there are some issues in current GitHub Action: https://www.githubstatus.com/. Let's wait for a while and see whether it can be fixed from their end.

**Comment by jcwchen** [comment]
Please allow me to reopen this PR to trigger CIs.

**Comment by hamptonm1** [comment]
> Please allow me to reopen this PR to trigger CIs.

Thank you! Let me know if this is okay to merge.

**Comment by hamptonm1** [comment]
@jcwchen Sorry can you merge the PR? I do not have write access

**Pull request merged**
