### PR TITLE
Initialise weights and input with random values. 

### PR DESCRIPTION
**Pull request by newling**
Prior to this commit LSTM unit weights are initialized with 1. To make the test more robust, this commit initialises with uniform random values. Similarly for input data. Finally a cosmetic change: repeated code is removed.

### CODE REVIEW

**Comment by houseroad** [comment]
Please run `python onnx/defs/gen_doc.py` and `python onnx/backend/test/stat_coverage.py` to update Operators.md and TestCoverage.md.

**Comment by newling** [comment]
I'm going to start this PR again from scratch as I messed up (pulled instead of rebased).

**Comment by newling** [comment]
please see the second attempt at this PR : https://github.com/onnx/onnx/pull/1130

**Comment by newling** [comment]
@houseroad it's still failing the final CI test (now at https://github.com/onnx/onnx/pull/1130) after i ran your suggestion:

> Please run python onnx/defs/gen_doc.py and python onnx/backend/test/stat_coverage.py to update Operators.md and TestCoverage.md.

Maybe I should try a "dummy" pull request (just a blank line somewhere)  to see if that passes?

**Pull request closed without merging**
