### PR TITLE
Added test for 2D and 3D for average and max pool.

### PR DESCRIPTION
**Pull request by jendrikjoe**
I think merging it with the current pool request for average and test pooling could help.
I implemented tests for 2D and 3D max and mean pooling,
comparing the results to a calculation in numpy.
1D pooling still had issues using the caffe2
backend so I left them out for the time being.
In addition, the testing with the caffe2
backend still fails as it uses ceil to calculate the
size of tensors instead of floor. The values
for the existing entries still match though.

### CODE REVIEW

**Comment by houseroad** [comment]
@onnxbot test this please

**Comment by jendrikjoe** [comment]
@houseroad great thanks for the feedback :)

**Comment by houseroad** [comment]
@jendrikjoe we have landed the PRs on averagepool and maxpool. You can adjust your pr based on the existing functions. I would suggest provide several representative cases. :-)

**Comment by houseroad** [comment]
@jendrikjoe If you could update the PR according to existing test, it will be awesome!

**Comment by jendrikjoe** [comment]
@houseroad working on it :)

**Comment by bddppq** [comment]
Closing since these have been added by @fumihwh in #572 and #573

**Pull request closed without merging**
