### PR TITLE
Allow building onnxlib in SHARED mode.

### PR DESCRIPTION
**Pull request by linshokaku**
### Description

This enables building onnxlib in SHARED mode by specifying ONNX_BUILD_SHARED=ON.

### Motivation and Context

cf. #6394

### CODE REVIEW

**Comment by cyyever** [comment]
BUILD_SHARED_LIBS is the CMake variable for exactly this purpose.

**Comment by linshokaku** [comment]
Thank you for your comment! I have made the modifications to use BUILD_SHARED_LIBS.

**Comment by andife** [comment]
Do we need a test for that kind of build?

**Comment by cyyever** [comment]
You can set BUILD_SHARED_LIBS=ON , there is no need to introduce a new flag.

**Pull request closed without merging**
