### PR TITLE
Add include_last_pixel to pool for CoreML compatibility.

### PR DESCRIPTION
**Pull request by ebarsoum**
We found out that most CoreML pretrained models has 'last_pixel' attribute set for the pool OPs, as defined in:

https://apple.github.io/coremltools/coremlspecification/sections/NeuralNetwork.html#poolinglayerparams

I added this attribute in order to convert from CoreML pretrained model to ONNX. I am open to suggestion.

### CODE REVIEW

**Comment by Yangqing** [comment]
Now, if I understand it correctly, I should plead guilty for this one. It is an old behavior in Caffe that is very strongly discouraged nowadays, because it creates discrepancy between convolution and pooling. For more details, see the comment about history here:

https://github.com/caffe2/caffe2/blob/master/caffe2/proto/caffe2_legacy.proto#L23-L34

There are various discussions in the caffe repository history saying this is a bad choice, so I am in favor of not adding it for future looking purposes. Luckily, most of the frameworks nowadays no longer use this feature in default, and even Caffe moved on.

If we know the input size, this is a pretty much solvable during model conversion. Shall we consider correcting this discrepancy during conversion instead of adding this legacy argument (and drag history burden along)? :)

**Comment by Yangqing** [comment]
(and to make myself less guilty, the Caffe behavior was to be consistent with the earlier cuda-convnet behavior IIRC)

**Comment by ebarsoum** [comment]
@Yangqing  good to know who to blame...:) 

I would love to make this done in conversion and remove it from the API, I looked at that initially . However, there are 2 issues:
1. Won't work for unknown size image.
2. Even for known size input, some of the models you don't guaranty to have this information at the pool node input. In this case you will need to actually do inference during conversion.

**Comment by Yangqing** [comment]
If I recall correctly, most of the CoreML model actually has known sizes. CoreML's interface kind of derived from Caffe and it retains a lot of those assumptions, so 1 won't be an issue. For 2 - basically when there is a backend one can "play" the network to infer the size. It is done in both torch2caffe and caffe-to-caffe2 I believe. And you are right - one need to do inference during conversion. But IIRC this is better than dragging along an old issue :)

**Comment by ebarsoum** [comment]
For 2, how that will work with a converter? Converter don't have backend.

**Pull request closed without merging**
