### PR TITLE
Convert sphinx docs to markdown

### PR DESCRIPTION
**Pull request by justinchuby**
### Motivation and Context

Easier to maintain docs

https://github.com/executablebooks/rst-to-myst

### CODE REVIEW

**Comment by xadupre** [comment]
Was it necessary?

**Comment by jcwchen** [comment]
I am fine with either way (.rst or .md) as long as onnx and onnxscript are consistent (having same format to generate web content).

**Comment by justinchuby** [comment]
Imo it comes down to which format people like to use and maintain because they can coexist in a repo.

**Review by xadupre — APPROVED** [review]

**Comment by justinchuby** [comment]
@jcwchen this is ready

**Pull request merged**
