### PR TITLE
Bump protobuf to 5.28.3

### PR DESCRIPTION
**Pull request by cyyever**
### Description

Use a recent protobuf. README is left unchanged because it mentions the minimum supported protobuf.

### CODE REVIEW

**Comment by andife** [comment]
duplicate of https://github.com/onnx/onnx/pull/6167/ ?

**Comment by cyyever** [comment]
@justinchuby Review again?

**Comment by cyyever** [comment]
> duplicate of #6167 ?

Uses a more recent version while  leaving the document unchanged.

**Review by justinchuby — APPROVED** [review]

**Comment by justinchuby** [comment]
Looks like this change is causing errors:

https://github.com/onnx/onnx/actions/runs/11536904414/job/32113682442

```
    _descriptor.EnumValueDescriptor(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 920, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by cyyever** [comment]
@justinchuby That is because pip's protobuf is latest, while in ubuntu22.04, the system protobuf lib is too old.

**Pull request merged**
