### PR TITLE
update qops tests

### PR DESCRIPTION
**Pull request by askhade**
onnx qops spec states scale and zero point to be a scalar for some qops like convinteger/quantizelinear/dequantizelinear/qlinearconv where as the tests were using 1D tensor. Updating the tests to strictly follow the spec.

### CODE REVIEW

**Comment by linkerzhang** [comment]
@postrational

**Comment by linkerzhang** [comment]
the pytorch circleci failure should not be related to this PR. @spandantiwari @houseroad

**Comment by spandantiwari** [comment]
@linkerzhang @askhade Not sure why this test is failing. Will take a look.

**Comment by spandantiwari** [comment]
I think the test may have been fixed already. @houseroad could you please confirm?

**Comment by houseroad** [comment]
@spandantiwari yes, it is.

**Comment by askhade** [comment]
@linkerzhang , @houseroad : Can one of you merge this PR. Thanks!

**Comment by houseroad** [comment]
Let's wait the CI a bit. I would like to see the result to make sure it's fixed :-)

**Comment by askhade** [comment]
@spandantiwari , @houseroad circleci is failing again. Thanks

**Pull request merged**
