### PR TITLE
version bump to 7

### PR DESCRIPTION
**Pull request by zasdfgbnm**
As mentioned in: https://github.com/onnx/onnx/pull/869#issuecomment-386167530

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
How are the files in `onnx/examples/resources` generated? manually?

**Comment by houseroad** [comment]
@zasdfgbnm yes, manually.

I will update zoo later, and let you know when it's done.

**Comment by houseroad** [comment]
https://github.com/onnx/onnx/pull/887 will make sure, the ipython notebook won't be affected by bumping up the opset version.

**Comment by zasdfgbnm** [comment]
Looks to be unrelated failures on file `onnx/test/shape_inference_test.py`

**Comment by zasdfgbnm** [comment]
@houseroad Do you mean the .onnx files in `onnx/backend/test/data`?

**Comment by houseroad** [comment]
Such as `onnx/backend/test/data/node/test_log/test_data_set_0/input_0.pb`

**Comment by zasdfgbnm** [comment]
changes to these file are reverted now

**Pull request merged**
