### PR TITLE
Revert "Bump actions/upload-artifact from 3.1.3 to 4.0.0"

### PR DESCRIPTION
**Pull request by justinchuby**
Reverts onnx/onnx#5830. It is breaking the release pipeline.

https://github.com/actions/upload-artifact/issues/478

### CODE REVIEW

**Review by liqunfu — CHANGES_REQUESTED** [review]
I see the failure was due to same name of the same artifact exists. is the caused by: https://github.com/actions/upload-artifact?tab=readme-ov-file#not-uploading-to-the-same-artifact?

I have seen this before, onnx-weekly wheels are named by date so it may take another day to run the CI if a previous run just passed.

**Comment by justinchuby** [comment]
I think that’s a breaking change of the new upload action described in the link above

**Comment by liqunfu** [comment]
> I think that’s a breaking change of the new upload action described in the link above

But it is an intended breaking change. We have to deal with it or give feedback for them to revert this feature. I agree it is a very annoying thing.

**Review by liqunfu — APPROVED** [review]

**Comment by liqunfu** [comment]
> > I think that’s a breaking change of the new upload action described in the link above
> 
> But it is an intended breaking change. We have to deal with it or give feedback for them to revert this feature. I agree it is a very annoying change. Lets hold this PR for a day to confirm that a wheel with new date can be uploaded and merge this PR. We will then raise our voice to the action repo.

I was wrong that with no-scheduled action the wheel name has no date on it. So it is a blocking problem for us because we can no longer run release CI manually due to the change introduced by [actions/upload-artifact-4.0.0](https://github.com/onnx/onnx/tree/revert-5830-dependabot/github_actions/actions/upload-artifact-4.0.0).

**Pull request merged**
