### PR TITLE
using expm1

### PR DESCRIPTION
**Pull request by autoih**
using superior expm1 to calculate `exp(x) - 1`

### CODE REVIEW

**Comment by autoih** [comment]
Hi @prasanthpul, can you help review the PR when you are convenient?

**Comment by autoih** [comment]
Thanks @prasanthpul. I think it may be good if we have `expm1p` for the calculation `exp(x) - 1` to provide greater precision, according the [ref](https://en.wikipedia.org/wiki/Loss_of_significance), It only makes sense to use `expm1` when the computation requires like `exp(x) - 1`, and this is the exact cases of this PR.

**Comment by autoih** [comment]
Thanks @prasanthpul, would you please guide me how to fix the error raised by travis-ci? I am not sure why the build has been terminated. Thank you!

**Comment by postrational** [comment]
It seems the `Operators.md` will have to be regenerated or conflicts resolved otherwise.

**Pull request closed without merging**
