### PR TITLE
to_string for Android

### PR DESCRIPTION
**Pull request by yinghai**
Android doesn't have `std::to_string` and we need to in order to build with Caffe2 in Android. 

Code copied from https://github.com/caffe2/caffe2/blob/4f534fad1af9f77d4f0496ecd37dafb382330223/caffe2/core/common.h#L198-L206

### CODE REVIEW

**Comment by houseroad** [comment]
@onnxbot merge after CI pass

**Comment by houseroad** [comment]
Is this feature available already/

**Comment by yinghai** [comment]
> Is this feature available already/

What do you mean?

**Comment by houseroad** [comment]
I remember that @bddppq mentioned onnxbot may support more commands, something like this.

**Comment by yinghai** [comment]
@onnxbot retest this please

**Pull request merged**
