### PR TITLE
Add dilation attribute to MaxPool

### PR DESCRIPTION
**Pull request by karljang**
This PR adds the 'dilations' attribute to MaxPool operator, and it's solving #1378 issue.

### CODE REVIEW

**Comment by karljang** [comment]
Hi @houseroad, 
I've made it up to date.
I think the MaxPool with dilation is quite useful for speech recognition models.
Can I get this PR reviewed?

**Comment by karljang** [comment]
@houseroad 
I've added a dilation test case for MaxPool operator.
Thanks for your approval~

**Comment by houseroad** [comment]
friendly ping for review @ebarsoum @linkerzhang @raymondxyang

**Comment by karljang** [comment]
Thank you all~!

**Pull request merged**
