### PR TITLE
Bugfix in function shape/type inference

### PR DESCRIPTION
**Pull request by raymondxyang**
Fix a bug in accessing vector element

### CODE REVIEW

**Comment by raymondxyang** [comment]
Well it actually behave differently once the capacity of the vector is met and the memory spaces got reassigned..

**Comment by houseroad** [comment]
@raymondxyang could you give an example to elaborate the problem?

**Comment by raymondxyang** [comment]
Well.. it either caused seg fault or get typeproto with uninitialized fields. The test case is Full Connect function op, which has three inputs and triggers the reassignment of the vector elements addresses. we store them to quickly access its shape/type info within the function.

**Comment by snnn** [comment]
Or you may let temp_valueTypesByName take the ownership of these protobuf objects? Then you can delete temp_types_cache.

**Comment by raymondxyang** [comment]
@snnn its not easy to do it in that way.. The ctx.getInputType will return a const pointer, Which means there has to be a mutable copy of the typeproto object while there should also be a std::unordered_map<std::string, TypeProto*> to pass to the InferenceContextImpl()

**Pull request merged**
