### PR TITLE
Update governance to deal with steering committee vacancy

### PR DESCRIPTION
**Pull request by prasanthpul**
As discussed in Steering Committe, goal is to avoid costly and time-consuming mid-term election when dealing with a resignation since there is an annual election.

### CODE REVIEW

**Comment by andife** [comment]
Currently, the variant sounds pretty good to me. As stated in our Steering Committee discussion, I think it makes a lot of sense to avoid an election if necessary due to the short term of office. 
I would approve that pull request. (But maybe let's wait for a second opinion.)

**Comment by mk-nvidia** [comment]
The change looks fine to me as well (I don't see a button to add my approval)

**Review by andife — APPROVED** [review]

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM.

**Comment by prasanthpul** [comment]
> The change looks fine to me as well (I don't see a button to add my approval)

you should be able to now, @mk-nvidia

**Review by andife — APPROVED** [review]
sounds great!

**Review by gramalingam — APPROVED** [review]
Looks like other unrelated changes are cluttering up this PR? I suppose they are from others PRs merged into main already?

**Comment by prasanthpul** [comment]
yes it got messed up - new PR at https://github.com/onnx/onnx/pull/4811

**Pull request closed without merging**
