### PR TITLE
Fix some typos.

### PR DESCRIPTION
**Pull request by Yulv-git**
**Description**
Fix some typos.

**Motivation and Context**

Fix some typos for doc and comments.

### CODE REVIEW

**Review by jcwchen — COMMENTED** [review]
Thank you for catching these. To fix CI failure, please run
```
python onnx/defs/gen_doc.py
ONNX_ML=0 python onnx/defs/gen_doc.py
```
to regenerated Operators.md and Operators-ml.md from updated defs.cc and old.cc files.

**Comment by Yulv-git** [comment]
> Thank you for catching these. To fix CI failure, please run
> 
> ```
> python onnx/defs/gen_doc.py
> ONNX_ML=0 python onnx/defs/gen_doc.py
> ```
> 
> to regenerated Operators.md and Operators-ml.md from updated defs.cc and old.cc files.

Thanks for your help!

**Comment by jcwchen** [comment]
No problem! Please note that after updating defs.cc and old.cc, you will need to build ONNX from source (for instance, `pip install -e .`) before running document generation. It seems that you were not using the right installed ONNX in your latest commit so there are still some difference failure in CIs.

**Review by jcwchen — COMMENTED** [review]
Thanks for the quick update! Now the CIs all passed. One last thing: you need to sign-off all your commits by DCO: https://github.com/onnx/onnx/blob/main/CONTRIBUTING.md#dco

**Comment by Yulv-git** [comment]
> Thanks for the quick update! Now the CIs all passed. One last thing: you need to sign-off all your commits by DCO: https://github.com/onnx/onnx/blob/main/CONTRIBUTING.md#dco

Thanks for your guidance. There may be no problem with the current PR.

**Review by gramalingam — APPROVED** [review]

**Pull request merged**
