### PR TITLE
handle uint8 typed field in onnx checker

### PR DESCRIPTION
**Pull request by houseroad**
https://github.com/onnx/onnx/issues/1577

### CODE REVIEW

**Comment by houseroad** [comment]
@snnn

**Comment by snnn** [comment]
Thanks.

Could you also add INT16?

**Comment by houseroad** [comment]
Sure, will do it

**Comment by zrphercule** [comment]
Guess the test failed because of they didnt remove the catch check in pytorch.
I saw Peter removed it a few hours ago, let's retest it.

**Comment by linkerzhang** [comment]
looks like I clicked the merge too quickly. @houseroad  you're adding more to support 16 and adding test cases? :)

**Pull request merged**
