### PR TITLE
WIP: Test for Python 3.13

### PR DESCRIPTION
**Pull request by andife**

### CODE REVIEW

**Comment by andife** [comment]
Maybe of interest: https://pyreadiness.org/3.13/#:~:text=Python%203.13%20Readiness,-What%20is%20this&text=Python%203.13%20is%20a%20currently,explicitly%20support%20Python%203.13%20yet.

**Comment by andife** [comment]
google-re2 probably not ready for python 3.13
```

Downloading pycparser-2.22-py3-none-any.whl (117 kB)
Building wheels for collected packages: numpy, google-re2
  Building wheel for numpy (pyproject.toml): started
  Building wheel for numpy (pyproject.toml): finished with status 'done'
  Created wheel for numpy: filename=numpy-2.0.0-cp313-cp313-linux_x86_64.whl size=10106605 sha256=2679ab53b95feb57f77bf1aa520b39f5df05dfb0f4a012f7d6c0ef05f3e0b34c
  Stored in directory: /home/runner/.cache/pip/wheels/e0/d3/66/30d07c18e56ac859b5e8d3ceaf22f093a09bae124a472b85d1
  Building wheel for google-re2 (pyproject.toml): started
  Building wheel for google-re2 (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for google-re2 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-313
      creating build/lib.linux-x86_64-cpython-313/re2
      copying re2/__init__.py -> build/lib.linux-x86_64-cpython-313/re2
      running build_ext
      bazel build --extra_toolchains=//python/toolchains:all --compilation_mode=opt -- :all
      2024/09/09 16:34:30 Downloading https://releases.bazel.build/7.3.1/release/bazel-7.3.1-linux-x86_64...
      WARNING: Invoking Bazel in batch mode since it is not invoked from within a workspace (below a directory having a WORKSPACE file).
      Extracting Bazel installation...
      OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
      ERROR: The 'build' command is only supported from within a workspace (below a directory having a WORKSPACE file).
      See documentation at https://bazel.build/concepts/build-ref#workspace
      error: command '/usr/local/bin/bazel' failed with exit code 2
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for google-re2
```

**Comment by xadupre** [comment]
google-re2 is only needed for the reference evaluator so i can be removed when building onnx and the few unit test depending on google-re2 should be disabled when this package is missing. I suggest removing google-re2 as a dependency.

**Comment by andife** [comment]
https://numpy.org/news/

```
NumPy 2.1.0 released
18 Aug, 2024 – NumPy 2.1.0 provides support for Python 3.13 and drops support for Python 3.9. In addition to the usual bug fixes and updated Python support, it helps get NumPy back to its usual release cycle after the extended development of 2.0. The highlights for this release are:

Support for Python 3.13.
Preliminary support for free threaded Python 3.13.
Support for the array-api 2023.12 standard.
Python versions 3.10-3.13 are supported by this release.
```

Which refers back to my question here: https://github.com/onnx/onnx/issues/6298

**Comment by andife** [comment]
@xadupre 
Building works for 
Test ubuntu-24.04, 3.13.0-rc.2, External, debug=1, onnx_ml=1, doc=1
Test macos-latest, 3.13.0-rc.2, External, debug=1, onnx_ml=1, doc=1

Windows fails because of:

```
Run python setup.py build_ext --inplace
Traceback (most recent call last):
  File "D:\a\onnx\onnx\setup.py", line 24, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'
Traceback (most recent call last):
  File "D:\a\onnx\onnx\setup.py", line 24, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'
Error: Process completed with exit code 1.
```

We could manuelly install setuptools
https://conda-forge.org/news/2024/08/21/sunsetting-pip-deps/

**Pull request closed without merging**
