### PR TITLE
Do not infer shape when input shape is unknown

### PR DESCRIPTION
**Pull request by shinh**
Without this check, a scalar shape is wrongly inferred when
the input has an unknown shape. A test was added for ScatterND
since this op is sufferred by this issue.

### CODE REVIEW

**Comment by linkerzhang** [comment]
@shinh can you resolve the conflicts? thanks!

**Comment by shinh** [comment]
Resolved. CLA seems to be yellow long time. I've already signed the CLA (e.g., https://github.com/onnx/onnx/pull/2549)

**Comment by linkerzhang** [comment]
@shinh there're conflicts again :(. I can help to monitor and merge it when conflicts resolved and ci passes next time.

**Comment by shinh** [comment]
Just clicking "Update branch" button worked this time, thanks!

**Comment by linkerzhang** [comment]
The "Update branch" button may be only visible for you :), There's no such button shown on my view. You may need to click it again.

**Comment by shinh** [comment]
Ah, I see. I saw other people merged my PR to HEAD several times (e.g., https://github.com/onnx/onnx/pull/2620) and I thought maintainers have the access to the button. It seems my guess was wrong and they manually merged my PRs.

Anyway, I'll try merging this PR as often as I can. Thanks!

**Comment by shinh** [comment]
Now this was fixed by https://github.com/onnx/onnx/pull/2778

**Pull request closed without merging**
