### PR TITLE
six: remove all references

### PR DESCRIPTION
**Pull request by stillmatic**
ONNX has dropped python 2 support and does not need this anymore.

Signed-off-by: Chris Hua <hua.christopher@gmail.com>

**Description**
- Removes six and all references, replaces with equivalent python 3 syntax

**Motivation and Context**
- part of modernizing code base and supporting mypy upgrades
- other open PR is https://github.com/onnx/onnx/pull/3604, but has gotten quite unwieldy, looking to get smaller pieces merged first.

### CODE REVIEW

**Review by jcwchen — APPROVED** [review]
Thank you for removing six! After this PR is merged, https://github.com/onnx/onnx/pull/3604 this one would be closer to finishing.

**Comment by stillmatic** [comment]
Thanks! I think the path forward is to close #3604 in favor of this and other smaller PRs eg https://github.com/onnx/onnx/pull/3939, there is actually quite a lot of work to update as each mypy version brings in new requirements, and I think the original PR accidentally masks lots of them.

**Review by askhade — APPROVED** [review]
LGTM

**Comment by askhade** [comment]
@stillmatic : Please fix the unused import alert. Then we can merge this PR.

image

**Review by askhade — CHANGES_REQUESTED** [review]
please fix unused import alert

**Review by askhade — APPROVED** [review]

**Pull request merged**
