### PR TITLE
python_out does not recognize dllexport_decl.

### PR DESCRIPTION
**Pull request by xkszltl**
Fix https://github.com/onnx/onnx/issues/2481

### CODE REVIEW

**Comment by xkszltl** [comment]
CI failure unrelated: `IPython 7.10+ supports Python 3.6 and above.`

**Comment by snnn** [comment]
LGTM

**Comment by linkerzhang** [comment]
can you also check the appveyor CI failure please? thank you!

**Comment by xkszltl** [comment]
@linkerzhang As commented earlier in this thread, it has nothing to do with this PR as the CI pipeline itself is broken.

> CI failure unrelated in python 3.5 builds: IPython 7.10+ supports Python 3.6 and above.

**Pull request merged**
