### PR TITLE
Ignore the format PR in git blame

### PR DESCRIPTION
**Pull request by justinchuby**
### Description

Ignore the format PR(fddb2b6d4ea3fb3dba751d884865042503260899) in git blame

### Motivation and Context

So that github does not show the formatting PR in blame which obscures the history.

### CODE REVIEW

**Review by gramalingam — COMMENTED** [review]
LGTM, thanks!

**Review by jcwchen — APPROVED** [review]
Nice method!

**Comment by jcwchen** [comment]
nit: @justinchuby do you think it is good to include other commits about formatting as well? e.g., https://github.com/onnx/onnx/pull/4212, https://github.com/onnx/onnx/pull/4084.

**Comment by justinchuby** [comment]
Sure

**Comment by justinchuby** [comment]
Done

**Pull request merged**
