### PR TITLE
Handle negative axis in scan shape inference

### PR DESCRIPTION
**Pull request by gramalingam**
(Follow up to PR https://github.com/onnx/onnx/pull/1737) 
Extend shape inference to handle negative axes. Add shape inference test with negative axes.

### CODE REVIEW

**Comment by gramalingam** [comment]
@houseroad this addresses a couple of comments on PR 1737, to handle negative axes in the shape inference of the scan operator. Sorry I couldn't get it into PR 1737 before it was merged in.

**Comment by skottmckay** [comment]
Looks good to me. 

Also includes a bugfix when setting up the inputs to the subgraph inferencing where it was incorrectly starting at input 1 (which is correct for Scan 8 to skip the sequence_lens input, but not for Scan 9).

**Comment by linkerzhang** [comment]
@houseroad please kindly review, though I'm assuming that this change should be good as it only adds more coverage for shape inference function and adds more test cases accordingly.

**Comment by houseroad** [comment]
The code randomly hangs on some CI instances.

**Pull request merged**
