### PR TITLE
add output shape as input for reshape

### PR DESCRIPTION
**Pull request by linkerzhang**
if we all agree, test case will be added :).

### CODE REVIEW

**Comment by fumihwh** [comment]
Just a question, why do we need attribute `shape` and input `output_shape` both for defining the shape of output tensor?

**Comment by linkerzhang** [comment]
@fumihwh we don't need both definitely. that's why I'm adding "output_shape" as optional for backward compatibility.  but as @bddppq said, if we all agree to make a breaking change here, it's a cleaner way. Let me do that and see whether there're any other concerns from other folks.

**Comment by bddppq** [comment]
This change will pretty much break all models since I imagine Reshape is widely used.
One idea we have discussed before is for each breaking change we also provide a conversion/migration script to upgrade the existing models. Shall we use this as an opportunity to figure out such a mechanism? :-) cc @dzhulgakov @ezyang

**Comment by linkerzhang** [comment]
Looks good! Thank you so much! @bddppq

**Pull request merged**
