### PR TITLE
Add MultiHeadAttention Operator

### PR DESCRIPTION
**Pull request by lzu-zhanghr**
**MultiHeadAttention Operator**
- Implement mulriheadattention operator in onnx version 11.

**Motivation**
-  Transformer model is indispensable in computer vision and natural language process.
- Transformer Encoder and Transformer Decoder are too complex, while MultiHeadAttension is simplified and exists in both of them.

### CODE REVIEW

**Comment by lzu-zhanghr** [comment]
found synax error

**Comment by WilliamTambellini** [comment]
Hi @lzu-zhanghr  
Have you thought about first adding a DPA op and then a MHA:
DPA-MHA
?

**Comment by lzu-zhanghr** [comment]
> Hi @lzu-zhanghr Have you thought about first adding a DPA op and then a MHA: DPA-MHA ?
Thanks for your advice. I was planning to add multi-head attention, transformer-encoder, and transformer-decoder operators. Now, I will take Dot-Product Attention operator as my next task.

**Comment by lzu-zhanghr** [comment]
@WilliamTambellini I have added a [scaled dot-product attention operator](https://github.com/onnx/onnx/pull/4311).

**Pull request closed without merging**
