### PR TITLE
Update VersionConverter.md

### PR DESCRIPTION
**Pull request by RobertHenry6bev**
fix typo

**Description**
- Describe your changes.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Review by jcwchen — COMMENTED** [review]
Thanks for catching it. Please sign DCO. (https://github.com/onnx/onnx/blob/main/CONTRIBUTING.md#dco)

**Review by gramalingam — APPROVED** [review]

**Comment by RobertHenry6bev** [comment]
I can not figure out how to git push from my command line with the github
supplied pat.  I've spent 20 minutes on this, which is waaay more than I
should have to do for a 1 word fix from the GUI to github.

I am Robert R. Henry aka ***@***.***

**Comment by jcwchen** [comment]
> I can not figure out how to git push from my command line with the github supplied pat. I've spent 20 minutes on this, which is waaay more than I should have to do for a 1 word fix from the GUI to github. I am Robert R. Henry aka ***@***.***

Since there is only one commit which was not signed-off, you can use the commands below:
```
git commit --amend --signoff    # sign-off previous commit
git push -f  # force push to modify previous commit remotely
```

**Review by jcwchen — COMMENTED** [review]
@RobertHenry6bev Do you have bandwidth to fix the DCO issue? If not, please allow me to send a duplicate PR of yours and go forward. Thank you for your contribution.

**Comment by RobertHenry6bev** [comment]
I do not have the bandwidth to jump through all of the hoops to certify
myself as a valid OSS contributor to this project. Too daunting of a
gauntlet for the time and patience I had for a one-off typo fix.

Please file a separate PR for this fix.

Robert Henry
***@***.***

**Comment by gramalingam** [comment]
@RobertHenry6bev : thanks for the fix you suggested. I agree this is a lot of overhead for such a small fix, but unfortunately that's required as of now. For small fixes, please feel free to suggest it as an issue, and we can try to create a PR. Contributions in any form are greatly appreciated, thanks!

**Comment by jcwchen** [comment]
I created a duplicate PR and this was superseded by https://github.com/onnx/onnx/pull/4094. Thus close this one. Thank you for your contribution!

**Pull request closed without merging**
