### PR TITLE
[LICENSE] update license to Apache License v2.0

### PR DESCRIPTION
**Pull request by szha**
Signed-off-by: Sheng Zha <zhasheng@amazon.com>

### CODE REVIEW

**Comment by askhade** [comment]
CIs are failing because you manually updated some auto generated files... 
You will have to update and run the following scripts 
For TestCoverage.md --> onnx/backend/test/stat_coverage.py
For Operators.md and ChangeLog.md --> onnx/defs/gen_doc.py

And then run 
python onnx/backend/test/stat_coverage.py
python onnx/defs/gen_doc.py (generates the ml versions of the doc)
ONNX_ML=0 python onnx/defs/gen_doc.py

**Comment by szha** [comment]
@askhade any idea what causes the windows pipelines to fail?

**Comment by szha** [comment]
Finally passed. It turns out the problem was due to the newline format in `.bat` files.

**Review by askhade — APPROVED** [review]

**Comment by prasanthpul** [comment]
This PR updates dynamically generated files. Instead of updating those files directly, the script(s) that generates them should be updated. Otherwise checks will fail later on.

@askhade is it just operators.md and operators-ml.md? or are there other files too?

**Comment by szha** [comment]
I did update [gen_doc.py](https://github.com/onnx/onnx/pull/3159/files?file-filters%5B%5D=.py#diff-97f1e96d2673b6d783466c78c3fc625b407a252f4971c766c26946477b3d2929) and [stat_coverage.py](https://github.com/onnx/onnx/pull/3159/files?file-filters%5B%5D=.py#diff-8c9869d456aaf3eb6a715eea4ad032e175d47c33d4e1bdd7dcc3b2eb95c0f8fe) and the updated related `.md` files are direct outputs from them.

**Comment by prasanthpul** [comment]
@szha  thank you!!
I missed it

**Review by prasanthpul — APPROVED** [review]

**Review by gramalingam — APPROVED** [review]

**Pull request merged**
