### PR TITLE
Test Math Operator:  Clip, Div, Mul, Pow, Sub; Elu, LeakyRelu, Selu, HardSigmoid

### PR DESCRIPTION
**Pull request by tianleiwu**
Add default attribute values for LeakyRelu and HardSigmoid.

### CODE REVIEW

**Comment by tianleiwu** [comment]
Pow does not support broadcast. I propose to add broadcast in another pull request later.

**Comment by houseroad** [comment]
BTW, thanks a lot for the contribution.

**Comment by tianleiwu** [comment]
Added manually crafted input tensors for test examples.

**Comment by houseroad** [comment]
@onnxbot add to whitelist

**Pull request merged**
