### PR TITLE
Delete duplicate word in comment

### PR DESCRIPTION
**Pull request by haohaibo**

### CODE REVIEW

**Comment by gramalingam** [comment]
Can you also generate the other proto files that are generated from onnx.in.proto and check them in?

**Comment by haohaibo** [comment]
Re-generated onnx.proto and onnx.proto3

**Comment by haohaibo** [comment]
> Can you also generate the other proto files that are generated from onnx.in.proto and check them in?

**Comment by gramalingam** [comment]
There are also the onnx.ml versions of the protobuf: if you use genproto.py, the option "-ml" will generate the onnx-ml version protos.

**Comment by haohaibo** [comment]
Thanks for your kindly reminder. I used gen_proto.py option "--ml --lite" to re-generate `onnx-ml.proto` and `onnx-ml.proto3` files

**Comment by haohaibo** [comment]
Hi @gramalingam This PR has been pending for about 7 days.

**Pull request merged**
