### PR TITLE
Add missing header in shape_inference.h

### PR DESCRIPTION
**Pull request by jcwchen**
### Description

Add missing header: <algorithm> in shape_inference.h.

### Motivation and Context

Closes https://github.com/onnx/onnx/issues/5346. If using shape_inference.h independently, it cannot use std::transform because `<algorithm>` is not included.

### CODE REVIEW

**Review by gramalingam — APPROVED** [review]

**Comment by justinchuby** [comment]
I also found the following via cpplint:

```cpp
onnx/checker.h:51:  Add #include <utility> for move  [build/include_what_you_use] [4]
onnx/checker.h:159:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/common/file_utils.h:22:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/common/ir.h:205:  Add #include <set> for set<>  [build/include_what_you_use] [4]
onnx/common/ir.h:1178:  Add #include <utility> for move  [build/include_what_you_use] [4]
onnx/common/ir.h:1223:  Add #include <limits> for numeric_limits<>  [build/include_what_you_use] [4]
onnx/common/ir_pb_converter.h:35:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/common/ir_pb_converter.h:46:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/common/status.h:77:  Add #include <utility> for move  [build/include_what_you_use] [4]
onnx/common/stl_backports.h:49:  Add #include <utility> for forward  [build/include_what_you_use] [4]
onnx/common/tensor.h:169:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/common/tensor.h:216:  Add #include <utility> for move  [build/include_what_you_use] [4]
onnx/common/tensor.h:233:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/defs/attr_proto_util.h:22:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/defs/attr_proto_util.h:37:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/defs/controlflow/utils.h:13:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/defs/data_propagators.h:79:  Add #include <utility> for move  [build/include_what_you_use] [4]
onnx/defs/function.h:55:  Add #include <utility> for move  [build/include_what_you_use] [4]
onnx/defs/printer.h:44:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/defs/schema.h:1180:  Add #include <utility> for pair<>  [build/include_what_you_use] [4]
onnx/defs/shape_inference.h:541:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/defs/shape_inference.h:722:  Add #include <utility> for forward  [build/include_what_you_use] [4]
onnx/defs/shape_inference.h:844:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/defs/tensor/utils.h:49:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/defs/tensor_proto_util.h:18:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/defs/tensor_util.h:12:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/proto_utils.h:59:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/proto_utils.h:64:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/shape_inference/implementation.h:46:  Add #include <unordered_set> for unordered_set<>  [build/include_what_you_use] [4]
onnx/shape_inference/implementation.h:278:  Add #include <memory> for unique_ptr<>  [build/include_what_you_use] [4]
onnx/shape_inference/implementation.h:399:  Add #include <utility> for move  [build/include_what_you_use] [4]
onnx/shape_inference/implementation.h:474:  Add #include <unordered_map> for unordered_map<>  [build/include_what_you_use] [4]
onnx/shape_inference/implementation.h:493:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/shape_inference/implementation.h:495:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/BaseConverter.h:35:  Add #include <map> for map<>  [build/include_what_you_use] [4]
onnx/version_converter/BaseConverter.h:35:  Add #include <unordered_map> for unordered_map<>  [build/include_what_you_use] [4]
onnx/version_converter/BaseConverter.h:49:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/BaseConverter.h:86:  Add #include <memory> for make_unique<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/adapter.h:37:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/adapter.h:57:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/axes_attribute_to_input.h:18:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/axes_attribute_to_input.h:24:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/axes_attribute_to_input.h:36:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/axes_input_to_attribute.h:21:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/axes_input_to_attribute.h:33:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/axes_input_to_attribute.h:51:  Add #include <utility> for forward  [build/include_what_you_use] [4]
onnx/version_converter/adapters/axes_input_to_attribute.h:51:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/batch_normalization_13_14.h:27:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/broadcast_backward_compatibility.h:18:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/broadcast_backward_compatibility.h:29:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/broadcast_backward_compatibility.h:49:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/broadcast_forward_compatibility.h:18:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/broadcast_forward_compatibility.h:57:  Add #include <utility> for forward  [build/include_what_you_use] [4]
onnx/version_converter/adapters/broadcast_forward_compatibility.h:57:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/broadcast_forward_compatibility.h:75:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/cast_9_8.h:25:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/clip_10_11.h:48:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/compatible.h:18:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/compatible.h:21:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/dropout_11_12.h:37:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/extend_supported_types.h:25:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/extend_supported_types.h:38:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/extend_supported_types.h:49:  Add #include <unordered_set> for unordered_set<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/extend_supported_types.h:94:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/gemm_6_7.h:28:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/gemm_6_7.h:47:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/gemm_7_6.h:29:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/gemm_7_6.h:53:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/gridsample_19_20.h:27:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/maxpool_8_7.h:27:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/no_previous_version.h:19:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/no_previous_version.h:22:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/pad_10_11.h:26:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/pad_10_11.h:46:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/remove_consumed_inputs.h:18:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/remove_consumed_inputs.h:21:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/reshape_4_5.h:39:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/reshape_5_4.h:32:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/reshape_5_4.h:50:  Add #include <utility> for forward  [build/include_what_you_use] [4]
onnx/version_converter/adapters/reshape_5_4.h:50:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/reshape_5_4.h:62:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/resize_10_11.h:25:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/resize_10_11.h:40:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/scan_8_9.h:28:  Add #include <utility> for move  [build/include_what_you_use] [4]
onnx/version_converter/adapters/scan_8_9.h:49:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/scan_8_9.h:55:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/scan_9_8.h:29:  Add #include <utility> for move  [build/include_what_you_use] [4]
onnx/version_converter/adapters/scan_9_8.h:76:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/scan_9_8.h:82:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/scatter_10_11.h:35:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/slice_9_10.h:21:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/slice_9_10.h:44:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/softmax_12_13.h:51:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/softmax_12_13.h:77:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/split_12_13.h:23:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/split_12_13.h:34:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/split_13_12.h:20:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/split_13_12.h:32:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/split_13_12.h:50:  Add #include <utility> for forward  [build/include_what_you_use] [4]
onnx/version_converter/adapters/split_13_12.h:50:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/split_17_18.h:26:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/sum_8_7.h:26:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/sum_8_7.h:31:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/topk_9_10.h:21:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/topk_9_10.h:33:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/transformers.h:56:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/transformers.h:65:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/transformers.h:66:  Add #include <utility> for move  [build/include_what_you_use] [4]
onnx/version_converter/adapters/type_restriction.h:19:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/type_restriction.h:36:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/type_restriction.h:42:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/upsample_6_7.h:31:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/upsample_6_7.h:33:  Add #include <utility> for move  [build/include_what_you_use] [4]
onnx/version_converter/adapters/upsample_6_7.h:38:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/upsample_8_9.h:24:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/upsample_8_9.h:40:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/upsample_9_10.h:19:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/upsample_9_10.h:34:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/upsample_9_8.h:26:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/adapters/upsample_9_8.h:58:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/adapters/upsample_9_8.h:68:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/convert.h:60:  Add #include <map> for map<>  [build/include_what_you_use] [4]
onnx/version_converter/convert.h:95:  Add #include <utility> for pair<>  [build/include_what_you_use] [4]
onnx/version_converter/convert.h:95:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/convert.h:95:  Add #include <unordered_map> for unordered_map<>  [build/include_what_you_use] [4]
onnx/version_converter/convert.h:386:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/version_converter/convert.h:561:  Add #include <memory> for make_unique<>  [build/include_what_you_use] [4]
onnx/version_converter/helper.h:21:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
```

**Comment by justinchuby** [comment]
As well as

```
--filter=-,+build/include_what_you_use
onnx/checker.cc:448:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/checker.cc:701:  Add #include <functional> for equal_to<>  [build/include_what_you_use] [4]
onnx/checker.cc:1051:  Add #include <set> for set<>  [build/include_what_you_use] [4]
onnx/checker.cc:1051:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/common/ir_pb_converter.cc:175:  Add #include <utility> for move  [build/include_what_you_use] [4]
onnx/common/ir_pb_converter.cc:250:  Add #include <unordered_map> for unordered_map<>  [build/include_what_you_use] [4]
onnx/common/ir_pb_converter.cc:307:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/common/ir_pb_converter.cc:460:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/common/ir_pb_converter.cc:591:  Add #include <unordered_set> for unordered_set<>  [build/include_what_you_use] [4]
onnx/common/ir_pb_converter.cc:701:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/defs/attr_proto_util.cc:30:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/defs/attr_proto_util.cc:59:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/defs/controlflow/utils.cc:192:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/defs/controlflow/utils.cc:292:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/defs/function.cc:70:  Add #include <map> for map<>  [build/include_what_you_use] [4]
onnx/defs/math/utils.cc:24:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/defs/parser.cc:488:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/defs/printer.cc:92:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/defs/reduction/utils.cc:28:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/defs/reduction/utils.cc:110:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/defs/schema.cc:834:  Add #include <utility> for make_pair  [build/include_what_you_use] [4]
onnx/defs/shape_inference.cc:455:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/defs/tensor/utils.cc:33:  Add #include <limits> for numeric_limits<>  [build/include_what_you_use] [4]
onnx/defs/tensor/utils.cc:38:  Add #include <algorithm> for max  [build/include_what_you_use] [4]
onnx/defs/tensor/utils.cc:294:  Add #include <utility> for swap  [build/include_what_you_use] [4]
onnx/defs/tensor/utils.cc:390:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/defs/tensor/utils.cc:462:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/defs/tensor_proto_util.cc:129:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/defs/tensor_util.cc:21:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/inliner/inliner.cc:341:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/inliner/inliner.cc:357:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/inliner/inliner.cc:497:  Add #include <utility> for pair<>  [build/include_what_you_use] [4]
onnx/shape_inference/implementation.cc:954:  Add #include <utility> for move  [build/include_what_you_use] [4]
onnx/shape_inference/implementation.cc:960:  Add #include <unordered_map> for unordered_map<>  [build/include_what_you_use] [4]
onnx/shape_inference/implementation.cc:997:  Add #include <unordered_set> for unordered_set<>  [build/include_what_you_use] [4]
onnx/shape_inference/implementation.cc:1064:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
onnx/shape_inference/implementation.cc:1074:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/convert.cc:123:  Add #include <string> for string  [build/include_what_you_use] [4]
onnx/version_converter/convert.cc:133:  Add #include <memory> for shared_ptr<>  [build/include_what_you_use] [4]
onnx/version_converter/helper.cc:67:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
```

**Comment by jcwchen** [comment]
> I also found the following via cpplint:

Thank you for catching all these! I will update them when I have more time. Do you think it will be useful/easy to have such a similar Lint check in ONNX Lint CI?

**Comment by gramalingam** [comment]
Is there a way to automate these changes? Seems like a lot of them

**Comment by justinchuby** [comment]
> Is there a way to automate these changes? Seems like a lot of them

Good question. I did a quick search and didn't find any. I wish there were better tools. Or maybe use an ide? VS? CLion?

**Comment by jcwchen** [comment]
I prefer to merge this PR first to faster unblock build issues: #5369, #5346 in the main branch. Will have another PR to fix all globally.

**Pull request merged**
