### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by hanzhaogang**
since cmake v3.12, variable "PythonInterp" and "PythonLibs" has been changed into "Python"
see https://cmake.org/cmake/help/v3.12/module/FindPython.html for details.

see details for this issue: #1625

### CODE REVIEW

**Comment by snnn** [comment]
The old code works fine with cmake 3.12.

**Comment by hanzhaogang** [comment]
@snnn see this link: [https://cmake.org/cmake/help/v3.12/module/FindPythonLibs.html?highlight=findpythonlibs](https://cmake.org/cmake/help/v3.12/module/FindPythonLibs.html?highlight=findpythonlibs), it says: FindPythonLibs 

> Deprecated since version 3.12: Use FindPython3, FindPython2 or FindPython instead.


But actually I don't know the reason why you didn't hit this issue under cmake 3.12. Maybe there are some other reasons for the issue #1625 ? For me I fix this issue by the updated CMakeList.txt (with cmake 3.12).

**Comment by snnn** [comment]
It's deprecated, not removed. We don't have to do anything for that.

**Comment by houseroad** [comment]
Close the PR since the change is not necessary. Btw, thanks for the PR anyway.

**Comment by skottmckay** [comment]
I think it's necessary. Without the change the cmake generation fails on Windows with CMake > 3.12.

_CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES) (found suitable
  version "3.7.1", minimum required is "3.7")_

If you run the cmake generation again it will work so something gets cached from the first attempt, however it would be better to work the first time wouldn't it?

**Comment by ayermolo** [comment]
Also seeing this issue. Running twice bypasses it, but it's kind of a hack.

**Comment by snnn** [comment]
LGTM.

**Pull request closed without merging**
