### PR TITLE
clarify clip with min>max

### PR DESCRIPTION
**Pull request by AlexandreEichenberger**
### Description
Added the handling of min > max to the clip operator. It was previously unspecified how to handle that case, now the specs are more precise and match python/pytorch.

No implementation changes were necessary in the reference implementation as it already used the python clip operator.

### Motivation and Context

Some users asked about this corner case, and the present PR aims to specify precisely how this corner case is handled. It now matches Pytorch & Python. Tensorflow is unspecified in this respect, so no conflicts are introduced.

Background issue is here: https://github.com/onnx/onnx/issues/6165

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
Thanks @gramalingam for pointers on what to include in the PR, much appreciated.

**Review by gramalingam — APPROVED** [review]
LGTM, thanks!

**Comment by AlexandreEichenberger** [comment]
Added @gramalingam 's suggestion `Thus, this is equivalent to 'Min(max, Max(input, min))'.` to the explanation of Clip

**Comment by AlexandreEichenberger** [comment]
Not sure of the protocol, if it is approved, can it be merged or there need to be a further discussion at our next monthly SIG Operator meeting.

**Comment by gramalingam** [comment]
> Not sure of the protocol, if it is approved, can it be merged or there need to be a further discussion at our next monthly SIG Operator meeting.

Coincidentally, we had the Operator SIG meeting today, and did discuss this already. We can merge this.

**Pull request merged**
