### PR TITLE
Remove usage of numpy aliases for builtins (#3305)

### PR DESCRIPTION
**Pull request by SnoopJeDi**
As described in #3305, beginning in [NumPy 1.20](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations), the use of type aliases for builtin types (`np.object, np.bool, np.int`, etc.) is deprecated. This raises a `DeprecationWarning` when used in `onnx`.

This PR replaces deprecated usage with NumPy's official recommendations.

### CODE REVIEW

**Comment by mkbhanda** [comment]
@SnoopJeDi -- I am a newbie, from a grep/replace perspective this looks good. I upgraded to jumpy 1.20 and just installed ONNX. How/what do I build to get the deprecation warnings?  Also since your PR looks like we have some branch conflicts.
Regards

**Comment by jgerityneurala** [comment]
@mkbhanda all you need to do is `import onnx` to trigger the deprecation warnings, see #3305 for more information about the issue this PR fixes.

Thanks for pointing out the conflicts, I've rectified those.

**Comment by SnoopJeDi** [comment]
@mkbhanda all you need to do is `import onnx` to trigger the deprecation warnings, see #3305 for more information about the issue this PR fixes.

Thanks for pointing out the conflicts, I've rectified those.

**Review by mkbhanda — APPROVED** [review]
Confirmed using import that the deprecation warnings are gone.
LGTM

**Comment by nomaddo** [comment]
I miss this PR because of many warnings...
Does somebody is working for it?

**Comment by gromero** [comment]
Hi folks @linkerzhang @gramalingam any plan to land it soon? @SnoopJeDi I think there is now a conflict which needs to get fixed ? 

I'm pretty much interested on that fix since I get the same warnings when using that onnx module on TVM project CI.

Thanks!

**Comment by gramalingam** [comment]
LGTM, thanks!

**Review by gramalingam — APPROVED** [review]

**Pull request merged**
