### PR TITLE
Use RepeatedPtrField::Get instead of RepeatedPtrField::operator[], to be compatible with protobuf 3.0 API

### PR DESCRIPTION
**Pull request by jantonguirao**
Signed-off-by: Joaquin Anton <janton@nvidia.com>

**Description**
- Changes the usage for `RepeatedPtrField::operator[]` with `RepeatedPtrField::Get`, 

**Motivation and Context**
- Why is this change required? What problem does it solve?
The dev env setup suggests to install protobuf via `apt-get install python3-pip python3-dev libprotobuf-dev protobuf-compiler`.
This installs protobuf 3.0, which doesn't have `RepeatedPtrField::operator[]`. This PR replaces the usage of that API with `RepeatedPtrField::Get`, which is present in that version of Protobuf.

- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Review by gramalingam — APPROVED** [review]

**Review by jcwchen — APPROVED** [review]
> @jcwchen Do you know what is the minimum version of protobuf required by ONNX. I believe it'd be good to document that.

Now the minimum version of Protobuf required by ONNX is 3.12.2: https://github.com/onnx/onnx/blob/0fc92e41e3d66796b65ca67140e80640d834b27e/requirements.txt#L2.

**Comment by jantonguirao** [comment]
@jcwchen Do you know what is the minimum version of proto

> > @jcwchen Do you know what is the minimum version of protobuf required by ONNX. I believe it'd be good to document that.
> 
> Now the minimum version of Protobuf required by ONNX is 3.12.2. See [requirements.txt](https://github.com/onnx/onnx/blob/0fc92e41e3d66796b65ca67140e80640d834b27e/requirements.txt#L2).

In such case, [the documentation](https://github.com/onnx/onnx#linux) might be a bit misleading:
```
Ubuntu users: the quickest way to install protobuf is to run
apt-get install python3-pip python3-dev libprotobuf-dev protobuf-compiler
```
For instance, Ubuntu 18.04 has libprotobuf-dev on version 3.0.0, and Ubuntu 20.04 on version 3.6.1. Only Ubuntu 22.04 has a compatible version (3.12.4). I think we should clarify the documentation and recommend installation from source, at least for older versions of Ubuntu.

**Comment by jantonguirao** [comment]
@jcwchen @gramalingam I created https://github.com/onnx/onnx/pull/4360 to clarify about the required version in the documentation. Thanks

**Comment by jantonguirao** [comment]
> Sorry I wasn't clear about the required Protobuf version. Actually the minimum version of "Python" Protobuf required by ONNX is 3.12.2. I did see issues using Python Protobuf<=3.11: #3656.
> 
> By contrast, regarding proto/Protobuf compiler (different from Python Protobuf), IIUC, current ONNX has more compatibility with older Protobuf versions (3<=version<4 should be all fine).
> 
> A question: did you see issues from older Protobuf compiler version with the latest ONNX? Is it the reason why you propose this PR to make ONNX more compatible? If yes, I am thinking perhaps we can have new CIs to catch such kind of issues. Currently every CI uses Protobuf 3.16.0 as protoc.

Yes. Someone reported in the ONNX operator slack channel about a compiler error when installing protobuf from the ubuntu repositories:
```
/workspace/onnx_yuanyao/onnx/defs/sequence/defs.cc: In function 'bool onnx::BuildSequenceMapBodyFunc(const onnx::FunctionBodyBuildContext&, const onnx::OpSchema&, onnx::FunctionProto&)':
    /workspace/onnx_yuanyao/onnx/defs/sequence/defs.cc:675:40: error: no match for 'operator[]' (operand types are 'google::protobuf::RepeatedPtrField<onnx::ValueInfoProto>' and 'int')
             seq_at_node.add_output(g_inputs[inputIndex].name());
                                            ^
    /workspace/onnx_yuanyao/onnx/defs/sequence/defs.cc:683:37: error: no match for 'operator[]' (operand types are 'google::protobuf::RepeatedPtrField<onnx::ValueInfoProto>' and 'int')
             identity.add_output(g_inputs[inputIndex].name());
                                         ^
    /workspace/onnx_yuanyao/onnx/defs/sequence/defs.cc:741:30: error: no match for 'operator[]' (operand types are 'google::protobuf::RepeatedPtrField<onnx::ValueInfoProto>' and 'int')
         int64_t dtype = g_outputs[outputIndex].type().tensor_type().elem_type();
 ```
 
 I believe that CI should test with the minimum version (3.0?).

**Comment by jcwchen** [comment]
Thanks for the info. I have added a PR to make one of ONNX Linux CI use protoc from apt-get: https://github.com/onnx/onnx/pull/4365. It does catch this error. Let's forward your PR and then see whether there is other issue.

**Pull request merged**
