### PR TITLE
Not outputing the opset_version in the notebook example

### PR DESCRIPTION
**Pull request by houseroad**
Two benefits:
1) No need to update the notebook when bump up the opset version
2) Show an example to create and set opsetid in model

### CODE REVIEW

**Comment by houseroad** [comment]
@bddppq now i just don't output opset_version, the model is still the newest one.

**Comment by zasdfgbnm** [comment]
I think check_model, load_model, and optimize_onnx also print opset version.

**Comment by houseroad** [comment]
@zasdfgbnm but their model's opset version won't change when bumping up opset in the master.

**Comment by bddppq** [comment]
CI failure unrelated

**Pull request merged**
