### PR TITLE
Upgrade python syntax with pyupgrade

### PR DESCRIPTION
**Pull request by justinchuby**
**Description**

Upgrade python syntax with pyupgrade https://github.com/asottile/pyupgrade

```
pyupgrade --py36-plus --keep-runtime-typing **/*.py
```

**Motivation and Context**

Existing code contains obsolete python syntax. Using the tool to modernize the code base.

### CODE REVIEW

**Comment by justinchuby** [comment]
cc @jcwchen

**Review by jcwchen — COMMENTED** [review]
Thanks for proposing this PR! The CIs are failing. Probably you will need to use [update_doc.sh](https://github.com/onnx/onnx/blob/main/tools/update_doc.sh) to update Operators.md and Testcoverage.md because test files have been changed. Still, I am planning to merge a huge PR today: https://github.com/onnx/onnx/pull/3855 which will update a lot of test files as well. Perhaps you can update this PR after that PR gets merged. Thank you for waiting.

**Comment by jcwchen** [comment]
FYI: I just merged it. Please go ahead and update Operators.md and TestCoverage.md. Thanks!

**Comment by justinchuby** [comment]
> FYI: I just merged it. Please go ahead and update Operators.md and TestCoverage.md. Thanks!

Thanks! Will do

**Pull request closed without merging**
