### PR TITLE
Include pyi files in build

### PR DESCRIPTION
**Pull request by justinchuby**
https://github.com/onnx/onnx/pull/5697 should include pyi files but doesn't. This is because we do not have a required build dependency `protobuf` when the `build` module creates the isolated build environment. I added it as a required dependency and updated outdated configs.

- Include protobuf in build dependencies
- Raise an error instead of silently skip when `tools/protoc-gen-mypy.py` gets import error.

### CODE REVIEW

**Comment by justinchuby** [comment]
> Do you know what happened that caused the regression? ONNX 1.14 had pyi files while in 1.15 the pyi files are gone.

We moved from using setup.py to pyproject.toml. There may be a config error

**Comment by justinchuby** [comment]
> Thanks! Yeah I thought we had it even before this PR. I will double check the current builds first

True that we don't have them right now for some reason

**Review by gramalingam — APPROVED** [review]

**Comment by justinchuby** [comment]
So the pyi files in `onnx_cpp2py_export` are retained but those for the protos are lost. Looking into it

**Comment by justinchuby** [comment]
@BowenBao fixed. Updated root cause in description.

**Pull request merged**
