### PR TITLE
fix y in pow test case to scalar

### PR DESCRIPTION
**Pull request by fumihwh**
#819

### CODE REVIEW

**Comment by houseroad** [comment]
Thanks for fixing the problem!!!

**Comment by snnn** [comment]
Unfortunately, this fix doesn't really work.

After the fix, the ValueInfoProto of graph input y became:
```
name: "y"
type {
  tensor_type {
    elem_type: FLOAT
    shape {
    }
  }
}
```
It's perfect. But,

in onnx\defs\data_type_utils.cc, function  DataTypeUtils::ToString, we have such code:
```
 switch (type_proto.value_case()) {
    case TypeProto::ValueCase::kTensorType: {
      if (type_proto.tensor_type().has_shape() &&
          type_proto.tensor_type().shape().dim_size() == 0) {
        // Scalar case.
        return left + ToDataTypeString(type_proto.tensor_type().elem_type()) +
            right;
      } else {
        return left + "tensor(" +
            ToDataTypeString(type_proto.tensor_type().elem_type()) + ")" +
            right;
      }
    }
```

So the type string of this input would be 'float' , not 'tensor(float)'. 
It doesn't match the spec of 'Pow' .

**Comment by houseroad** [comment]
@snnn I think this change works perfectly. I manually checked the tensor proto and model proto the script generated. Their dims' len are both 0. I think what you want is here: https://github.com/onnx/onnx/pull/858. Or you want to add `floa16`, `float`, `double` to the type of second input.

**Comment by snnn** [comment]
Thanks.

**Pull request merged**
