### PR TITLE
Add more testcases from PyTorch operator test

### PR DESCRIPTION
**Pull request by houseroad**
Add a new type of backend testcases, 'pytorch-operator'.

### CODE REVIEW

**Comment by bddppq** [comment]
Are these test cases also auto-generated? If yes what's the difference between pytorch-operator and pytorch-converted?

**Comment by houseroad** [comment]
PyTorch converted test are test cases converted from pytorch tests.

PyTorch operator test are the test cases generated from [test_operators.py](https://github.com/onnxbot/onnx-fb-universe/blob/master/test/test_operators.py).

They are quite different, focus on different aspects, and test_operators.py are much easier to control. So I would like to separate pytorch operator test out.

**Comment by bddppq** [comment]
Ok separating them makes sense. However, I find the unittest class name "OnnxBackendPyTorchOperatorModelTest" looks a little bit weird :-)

**Comment by houseroad** [comment]
I admit that. ;-) Any suggestion? I suppose we name tests as OnnxBackend{}ModelTest.

**Comment by bddppq** [comment]
How about OnnxBackendPyTorchSimpleModelTest? :-)

**Comment by bddppq** [comment]
@onnxbot retest this please

**Comment by bddppq** [comment]
@onnxbot retest this please

**Pull request merged**
