### PR TITLE
fix a bug in func shape inference

### PR DESCRIPTION
**Pull request by souptc**
A bug in onnx function's shape inference function.

### CODE REVIEW

**Comment by linkerzhang** [comment]
@souptc Thank you! Please sign the CLA.

**Comment by souptc** [comment]
Hi, I tried to sing the cla, but the link above keep showing error: “There is no CLA to sign for onnx/onnx”, any one knows what's going on?

**Comment by linkerzhang** [comment]
@souptc it's showing "chentaMS" does not sign the CLA.

**Comment by souptc** [comment]
Hmm... it become tricky, to login as "chentaMS", it need the verification code by text message, but I didn't enable the global service on my us phone, and i am at China now... so I can't log in...

@linkerzhang , could anyone else take this change? it just one line change.

**Comment by souptc** [comment]
Finally get this done with my wife's help...

**Pull request merged**
