### PR TITLE
Fix timeout in MacOS-CI

### PR DESCRIPTION
**Pull request by jcwchen**
According to https://github.com/onnx/onnx/issues/2859, the MacOS-CI has a timeout problem.

### CODE REVIEW

**Comment by askhade** [comment]
This pipeline has passed in the past so what changed now? If without -y install halts for user input then how did this pipeline pass before?

**Comment by jacky82226** [comment]
> This pipeline has passed in the past so what changed now? If without -y install halts for user input then how did this pipeline pass before?

Since the setting here is fixed on our end, I think maybe there are some updates on conda package (need extra confirm for installing some packages). Setting yes should fix this issue.

**Comment by askhade** [comment]
> > This pipeline has passed in the past so what changed now? If without -y install halts for user input then how did this pipeline pass before?
> 
> Since the setting here is fixed on our end, I think maybe there are some updates on conda package (need extra confirm for installing some packages). Setting yes should fix this issue.

Do other CIs need a similar fix?

**Comment by jcwchen** [comment]
I did check other CIs:
For Linux-CI, the conda environment has been created initially before the scripts so it should be fine 
For Windows-CI, --yes has been added.
Thank you for pointing out.

**Pull request merged**
