### PR TITLE
bump version to 1.12.0

### PR DESCRIPTION
**Pull request by etiotto**
Signed-off-by: Ettore Tiotto <etiotto@ca.ibm.com>

**Description**
- prepare for 1.12.0 release

### CODE REVIEW

**Comment by etiotto** [comment]
Can one of the admin trigger the 6 workflows missing ?

**Comment by etiotto** [comment]
@liqunfu can you please help with the review?

**Comment by gramalingam** [comment]
@etiotto : it looks like the CI is failing due to some flake8 warnings about blank spaces in the python code.

**Comment by gramalingam** [comment]
===> check flake8
onnx/test/helper_test.py:349:28: W291 trailing whitespace
style check failed

**Comment by etiotto** [comment]
> ===> check flake8 onnx/test/helper_test.py:349:28: W291 trailing whitespace style check failed

I removed the white space now.

**Review by jcwchen — APPROVED** [review]
LGTM. Thank you for driving the release! There's still few pending PRs targeting 1.12. I hope that we can get them done today and let you cut the release branch.

**Comment by etiotto** [comment]
@liqunfu @jcwchen it just occur to me we probably should bump up the release to `1.12.0-rc1` (release candidate 1) to allow testing it with PiPy.  After all validation is done we can push a final PR to change the release version to 1.12.0 - opinions ?

**Comment by jcwchen** [comment]
> @liqunfu @jcwchen it just occur to me we probably should bump up the release to `1.12.0-rc1` (release candidate 1) to allow testing it with PiPy. After all validation is done we can push a final PR to change the release version to 1.12.0 - opinions ?

Yes, we will do it in the release branch after bumping the version to 1.12.0 in the main branch. So this PR is good to go. Thanks!

**Comment by jcwchen** [comment]
It seems all ONNX PRs targeting 1.12 have been merged.

**Comment by etiotto** [comment]
@jcwchen it seems this PR has passed CI but cannot be merged because is missing an approval. Who can approve?

**Comment by jcwchen** [comment]
It needs an approval from @onnx/sig-operators-approvers. @gramalingam Could you please help to approve this? Thank you.

**Pull request merged**
