### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by sjordan78**

### CODE REVIEW

**Comment by bddppq** [comment]
what is this for?

**Comment by sjordan78** [comment]
Hi! I'm new github and coding, I was trying to write code, but I seem to have made a mistake.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by houseroad** [comment]
Seems the PR was created mistakenly. So close.

**Comment by sjordan78** [comment]
Thank you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
