### PR TITLE
Suggesting Conv Pads Behavior

### PR DESCRIPTION
**Pull request by tjingrant**
> VALID mean no padding, therefore, read the pixel values from the pads attribute.

We cannot make sense of the logical consequence as evinced in the use of `therefore` here. Therefore in this PR we hope to resolve the conflict of auto_pad and pads in a more coherent way.

More specific reason for change, quoted from https://github.com/onnx/onnx/pull/166 

## Reason for change

> @ebarsoum This could be very confusing for the Tensorflow world as 'VALID' = no padding as opposed to no **auto** padding. On the other hand, we will try to put aside my presumptions from Tensorflow and explain the scheme that I think is the most intuitive:
> 
> You specify either autopad or pads. When both are specified, we should have a precedence established from discussion and take the one with higher precedence and abandon the one with lower precedence. 
> 
> Your current specification has the following aspects that we cannot understand/ do not feel good about:
> 
> 1. The interaction of auto_pad and pads are asymmetrical. Meaning that in some cases you go down to pads after looking at auto_pad whereas in some other cases you dont. Such asymmetrical behavior will lead to user having a hard time to memorize your specification and results in time wasted in looking up documentation and debugging.
> 
> 2. I do not see why anyone would specify audo_pad to be 'VALID' and then specify pads to be non-empty. Can you give me a specific use case? Why use 'VALID'  and nothing in the pads attribute in any case if you can just leave pads empty? 
> 
> 3. On a conceptually level, VALID is an automatic padding scheme (as manifested by its naming). You seem to take it as a partial padding scheme this is problematic because VALID option currently serves two purposes:
> - specify no padding is needed. (in which case no information is gained by having this 'VALID' paramter since we can leave pads empty).
> - specify users' intent that padding should be done according to the pads attribute (again, no information is gained by having this 'VALID' parameter since it is overiden).
> - So my question is why would we have this 'VALID' option? What information can be gained?
> 
> I hope you can understand our confusion coming from a Tensorflow world.

### CODE REVIEW

**Comment by ebarsoum** [comment]
So the proposed behavior change is that `pads` always override `auto_padding`, right?

**Comment by tjingrant** [comment]
@ebarsoum Yes, that way I believe it's a bit cleaner. Will change the other conv and pooling op spec in another commit if consensus can be reached here.

**Comment by bddppq** [comment]
How about do not allow setting both "auto_padding" and "pads"?

**Comment by tjingrant** [comment]
@bddppq that's even better, if onnx schema checker can automatically verify that (although I'm not sure if this is possible).

**Comment by gramalingam** [comment]
Yes, it seems cleaner to not allow both "auto_padding" and "pads".

**Comment by bddppq** [comment]
OpSchema and checker don't support declaring exclusive attributes yet. For now let's just document it.

**Comment by bddppq** [comment]
LGTM. @ebarsoum

**Comment by ebarsoum** [comment]
I am ok with this. So pads and auto_pad are exclusive...

**Pull request merged**
