### PR TITLE
Revert #3429

### PR DESCRIPTION
**Pull request by askhade**
Revet ""Fix RoiAlign backend test case output, and add new test case for an identity slice. (#3429)"

This reverts commit 82ddc566b950d05fdccb70c4579930f4014ece7f.

I merged too early

### CODE REVIEW

**Comment by gramalingam** [comment]
Is there some pending change required (just to know)?

**Comment by askhade** [comment]
> Is there some pending change required (just to know)?

Wei-Sheng had a few open comments regarding adding an optional attribute for alignment to maintain backward compatibility and bumping the op version. With this change more tests also need to be added which include this attr

**Review by gramalingam — APPROVED** [review]

**Comment by gramalingam** [comment]
I got the impression they agreed to decouple that change from this change. May be they can comment.

**Comment by gramalingam** [comment]
@fdwr @wschin for your feedback

**Review by wschin — APPROVED** [review]
Thanks! Either way works for me.

**Comment by fdwr** [comment]
>I got the impression they agreed to decouple that change from this change. May be they can comment.
Also, either way works for me. I can just re-cherry-pick what I already had again later.

**Review by fdwr — APPROVED** [review]

**Pull request merged**
