### PR TITLE
[Cherry-Pick] Fix main url checks (#6312)

### PR DESCRIPTION
**Pull request by roborags**
### Description
Cherry-Pick (#6312) - Fix main url checks into the `rel-1.17.0` branch

### Motivation and Context
Cherry pick commit to `rel-1.17.0` branch to target 1.17 release

### CODE REVIEW

**Review by justinchuby — APPROVED** [review]

**Review by gramalingam — APPROVED** [review]

**Comment by liqunfu** [comment]
protobuf 5.28 was release last week. It broke windows build:
https://github.com/protocolbuffers/protobuf/issues/18045

**Comment by roborags** [comment]
Do I have to wait for the protobuf issue to be fixed before merging ?
If not can I merge and go ahead with the next steps for 1.17.0 release ?

**Comment by liqunfu** [comment]
> Do I have to wait for the protobuf issue to be fixed before merging ? If not can I merge and go ahead with the next steps for 1.17.0 release ?

the newest protobuf 5.28.0 simply broke on Windows. This PR skip it. https://github.com/onnx/onnx/pull/6342

**Comment by liqunfu** [comment]
> > Do I have to wait for the protobuf issue to be fixed before merging ? If not can I merge and go ahead with the next steps for 1.17.0 release ?
> 
> the newest protobuf 5.28.0 simply broke on Windows. This PR skip it. #6342. Please cherry pick it when it is merged. Thank you

@roborags the PR is merged. PLease cherry-pick it so that the release-win CI can pass and then merge this PR.

**Comment by roborags** [comment]
Created PR #6347 to include protobuf testing update to `rel-1.17.0` branch.

**Pull request merged**
