### PR TITLE
[WIP] move all types into ONNX as agreed in infra SIG meeting.

### PR DESCRIPTION
**Pull request by linkerzhang**

### CODE REVIEW

**Comment by spandantiwari** [comment]
@linkerzhang - There are some CI failures. Would it be possible for you to update the branch? Let us know if we can help. Thanks for this PR. :-)

**Comment by BowenBao** [comment]
Should we keep the onnx-ml related proto files for now? It seems there are tests that depend on them.

**Comment by prasanthpul** [comment]
@BowenBao are the tests in ONNX? if so, they should be updated as part of this PR.

**Comment by linkerzhang** [comment]
I'll hold on this PR and work on a separate one to move Sequence and Map into ONNX domain firstly, since for SparseTensor type, there will be more updates. @gramalingam is working on that.

**Comment by spandantiwari** [comment]
cc: @bddppq - could you please review this PR. We are waiting for this to go in to get lists (Sequence) in ONNX so that we can enhance the support in PyTorch ONNX exporter.

**Pull request closed without merging**
