### PR TITLE
Set VERSION_NUMBER for release 1.7.0

### PR DESCRIPTION
**Pull request by chinhuang007**
Set VERSION_NUMBER back to 1.7.0 after validation for the
official release

### CODE REVIEW

**Comment by chinhuang007** [comment]
Please ignore for now. Some issues are found during testing. Will need to fix them before going back to the official release version number.

**Comment by linkerzhang** [comment]
adding @snnn for getting back to this PR with test status.

**Comment by snnn** [comment]
No progress now.

**Comment by linkerzhang** [comment]
@snnn @faxu would you help to update the status please?

**Comment by faxu** [comment]
The main issue is in SoftmaxCrossEntropyLoss - @codemzs is working on it and should have a fix validated this week. There are a few other minor issues that will also be fixed in the next couple days.

**Comment by chinhuang007** [comment]
@snnn @codemzs I believe we are waiting for https://github.com/onnx/onnx/pull/2680 to be approved and merged. If so, please address the comments by reviewers there. Thanks for your hard work!!

**Comment by codemzs** [comment]
@chinhuang007 We plan to merge that PR by 3/30, thank you for your patience.

**Comment by chinhuang007** [comment]
@codemzs Thanks for the update. That seems to further delay the projected completion of bug fixes (by the end of this week) and the release of 3/31. The PR was approved 20 minutes ago. So @linkerzhang @snnn could you help to merge it? I'd like to start adding new PRs to the release branch and publish a candidate to TestPypi for a final test ASAP. Thanks everyone for your help!

**Comment by codemzs** [comment]
@chinhuang007 The date for completion was set to 3/30 last week, what date was communicated to you?

**Comment by codemzs** [comment]
@linkerzhang @snnn Please do not merge the PR without consulting me.

**Comment by chinhuang007** [comment]
@codemzs The end of week estimate is coming in a note from Prasanth cced @faxu.
@prasanthpul This is to bring to your attention. If the bug fix completion is 3/30, as @codemzs stated above, I doubt there will be enough time to go through this PR, run the builder, conduct final test, and publish release 1.7 out to Pypi on 3/31.

**Comment by codemzs** [comment]
@chinhuang007 Seems like there was a miscommunication but we can get this in today afternoon. What is the latest you would like this in?

**Comment by chinhuang007** [comment]
To keep everything transparent, I already updated and announced the projected release schedule on gitter, https://gitter.im/onnx/Infra. I really think we should use it for better communication since the infra SIG owns the release process.

**Comment by codemzs** [comment]
@chinhuang007 I will keep this in mind for next time and will try to communicate better. While this is not an excuse but I'm fairly new to the project and still learning how releases happen. Can you please let me know what is the latest you would want this PR merged so that we can release on as promised on 03/31?

**Comment by chinhuang007** [comment]
@codemzs I am fairly new to the ONNX release process as well and really appreciate all the developers jumping in to help address critical issues. I would hope to see all release 1.7 PRs merged by this weekend. 
@linkerzhang @snnn  would you please confirm whenever we are ready for the release? I will wait for that signal to update this PR to start the final round of release verification. Thanks!

**Comment by codemzs** [comment]
@chinhuang007 Thanks for the flexibility! My goal is to get this in today if possible, just validating the results to be sure what we check-in is actually useful. The spec as you see already looks good.

**Comment by snnn** [comment]
@gramalingam Do you have any comments?

**Comment by gramalingam** [comment]
Hi @snnn : do you mean comments on the other PR (softmaxcrossentropyloss)? I am fine with it, I thought it had enough approvals already.

**Comment by snnn** [comment]
Is there a release candidate commit that ONNX Runtime team can use for testing?

**Comment by codemzs** [comment]
@snnn https://github.com/codemzs/onnx/tree/softmaxcrossentropyloss but need to address few minor comments before check-in this weekend.

**Comment by codemzs** [comment]
@chinhuang007 #2680 is ready to be merged and shipped with ONNX 1.7. One of the sig op approves will merge it. @wschin FYI

**Comment by chinhuang007** [comment]
@codemzs Thank you for taking care of this issue!

I just merged #2680 since it already has enough approvals.

@faxu @linkerzhang @snnn @prasanthpul 
I will reset the release branch, rel-1.7.0 to catch up to this commit. That means other critical PRs will be included as well. Please let me know if any objections. 

There is a discussion in infra gitter about IR version change, https://gitter.im/onnx/Infra. I am not sure if we need an IR change for release 1.7.0. Assuming no, I will create a new PR to reset the version number, 1.7.103 for the final release verification next.

**Comment by linkerzhang** [comment]
@chinhuang007 About IR version, I tried to clarify things in gitter room https://gitter.im/onnx/Infra. Let's see if there're different thoughts please, if no, the IR version should be bumped. Thank you!

**Pull request closed without merging**
