### PR TITLE
Shape inference support for conv with groups

### PR DESCRIPTION
**Pull request by varunjain99**
@bddppq @houseroad

### CODE REVIEW

**Comment by gramalingam** [comment]
I believe that the original check for groups was added because the behavior is different in the case of groups not being 1 (with a different shape inference required) … is this not the case?

**Comment by varunjain99** [comment]
@onnxbot retest this please

**Comment by bddppq** [comment]
@gramalingam IIUC the group number does not change the output shape

**Comment by bddppq** [comment]
@houseroad will do a follow up PR to update the spec that the size of the kernel's second dimension should be `C / g`

**Pull request merged**
