### PR TITLE
Fix conversion from split 11 to split 18. 

### PR DESCRIPTION
**Pull request by ZelboK**
Addresses #5222 

There does not exist a Split 12 from what I can see. I believe whomever made the conversion for Split 12 to Split 13 made a mistake and intended to do so for Split 11 to Split 13?

IIUC, the conversions should chain. Running this with my built ONNX changes seems to work fine

```
>>> import onnx
rt onnxruntime
model = onnx.load('simple_model_split.onnx')
model = onnx.version_converter.convert_version(model, 18)
onnx.checker.check_model(model)  # success
sess = onnxruntime.InferenceSession(model.SerializeToString())  # fail>>> import onnxruntime
>>> model = onnx.load('simple_model_split.onnx')
>>> model = onnx.version_converter.convert_version(model, 18)
>>> onnx.checker.check_model(model)  # success
>>> sess = onnxruntime.InferenceSession(model.SerializeToString())  # fail
>>>
>>> sess
<onnxruntime.capi.onnxruntime_inference_collection.InferenceSession object at 0x7f82dcce0a30>
>>>

>>> import onnxruntime as rt
>>> import numpy as np
>>> model_serialized = model.SerializeToString()
>>> sess = rt.InferenceSession(model_serialized)
>>> dummy_input = np.random.randn(1, 1, 28, 28).astype(np.float32)
 Perfo>>>
>>> outputs = sess.run(output_names=['output1', 'output2'],
...                    input_feed={'input': dummy_input})

>>> print(outputs)
[array([[[[ 4.02100086e-01,  1.91692543e+00,  5.60453236e-01, ...,
           1.10894358e+00, -9.10616279e-01,  2.63174176e-01],
         [ 9.16809678e-01,  8.39324117e-01,  1.30101681e+00, ...,
          -6.86384559e-01,  8.50693703e-01, -2.23367453e-01],
         [ 9.90843654e-01,  1.80581224e+00, -6.30877018e-01, ...,
          -4.17214930e-02,  9.42695260e-01, -9.54421163e-01],
```

Inferencing seems to work. I should remove the old split 12-> 13 converters but I would like confirmation from a contributor before I move forward.

### CODE REVIEW

**Comment by justinchuby** [comment]
There is a catch to this thing (which can be confusing): Split 11 implies (11, 12 ...) until a new version (13) is defined. In theory, we have 12->13, 17->18 already, which *should* be enough. From the issue it seems like the model is converted but turns out to be invalid.

Looking at the issue and code https://github.com/ZelboK/onnx/blob/3160a050150cc5bc5232c96be3a1bbed5187a264/onnx/version_converter/adapters/split_17_18.h#L25 this line should have handled the situation when `split` is not provided 🤔

**Comment by ZelboK** [comment]
> There is a catch to this thing (which can be confusing): Split 11 implies (11, 12 ...) until a new version (13) is defined. In theory, we have 12->13, 17->18 already, which _should_ be enough. From the issue it seems like the model is converted but turns out to be invalid.
> 
> Looking at the issue and code https://github.com/ZelboK/onnx/blob/3160a050150cc5bc5232c96be3a1bbed5187a264/onnx/version_converter/adapters/split_17_18.h#L25 this line should have handled the situation when `split` is not provided 🤔

Ah I see, I figured there was context I lacked. My bad 😅 . Would reproducing this in a test be trivial? Looking at hte issue again I don't see the model anywhere. I need to familiarize myself with the code flow and see where it is going wrong.

**Comment by gramalingam** [comment]
Justin is right. Version conversion is chained in this fashion. 

> this line should have handled the situation when `split` is not provided

It is not supposed to be `SetAttribute(...)` ! It should be `node->_i(...)` ... I am surprised this wasn't caught. Any unit-test should have caught this.

**Comment by ZelboK** [comment]
@gramalingam @justinchuby 

```
<
   ir_version: 6,
   opset_import: ["" : 11]
>
model (float[12,42] input) => (float[6,42] a, float[6,42] b) {
   a, b = Split <axis: int = 1> (input)
}
Model 11 is a valid ONNX model.
<
   ir_version: 6,
   opset_import: ["" : 18]
>
model (float[12,42] input) => (float[6,42] a, float[6,42] b) {
   a, b = Split <axis: int = 1, num_outputs: int = 2> (input)
}
Model 18 is a valid ONNX model.
```

From runing your script, this is what I get now @justinchuby

**Comment by justinchuby** [comment]
> Would it make sense to rename `SetAttribute`?

That would be good, but we have to maintain a stable public api.

**Review by justinchuby — APPROVED** [review]
Thanks a lot! 🙌

**Comment by justinchuby** [comment]
Could you check the DCO ci and sign off commits following its instructions?

**Comment by ZelboK** [comment]
Woops! Forgot to do so. Will do now.

**Pull request merged**
