### PR TITLE
Bump protobuf from 3.16.0 to 3.18.3

### PR DESCRIPTION
**Pull request by jcwchen**
### Description
Bump protobuf from 3.16.0 to 3.18.3 and the minimum supported Protobuf version is also bumped.

### Motivation and Context
Motivated by https://github.com/onnx/onnx/pull/4541, but this PR includes more necessary updates.

### CODE REVIEW

**Comment by cjvolzka** [comment]
When this is ready, is it something that would be back ported to the current 1.12 onnx release or would it wait for some future release (ie 1.13)?

**Comment by jcwchen** [comment]
> When this is ready, is it something that would be back ported to the current 1.12 onnx release or would it wait for some future release (ie 1.13)?

Good question. ONNX 1.13 release will probably happen this Nov. or Dec. However, for now I am even not sure whether this PR will be included in next 1.13 since this PR will upgrade ONNX's minimum supported version of Python Protobuf (3.12.2 -> 3.20.0). I will need more time to investigate whether it is OK for other ONNX related tools. May I understand your demand? (Is it also because of this issue https://github.com/onnx/onnx/security/dependabot/4?)

**Comment by cjvolzka** [comment]
@jcwchen I can't seem to access the link you provided. It's related to https://github.com/onnx/onnx/issues/4545 which references https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-8gq9-2x98-w8hf. 

Basically anyone who pulls in onnx and runs a dependency scanner is going to trip up on this. For our case onnx-mlir -> onnx -> protobuf.

**Comment by jcwchen** [comment]
> @jcwchen I can't seem to access the link you provided. It's related to https://github.com/onnx/onnx/issues/4545 which references [GHSA-8gq9-2x98-w8hf](https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-8gq9-2x98-w8hf).

Yes, thank you for providing the valid reference and that is the one I was talking about. I think it's good to have, but let me announce it for a while and see whether anyone has a concern about the upgrade. I will let you know when the decision is made. Thank you for waiting.

**Review by liqunfu — APPROVED** [review]

**Review by gramalingam — APPROVED** [review]

**Comment by jcwchen** [comment]
@cjvolzka FYI ONNX has bumped its used Protobuf version from 3.16.0 to 3.18.3. Thanks for waiting.

**Comment by AlexandreEichenberger** [comment]
@p-wysocki can we make sure that this PR will come in ONNX 1.13 release? Since it's merge, it appears that this will be the case, just wanting to make sure. Thanks.

**Pull request merged**
