### PR TITLE
Add PRelu test cases

### PR DESCRIPTION
**Pull request by tfujiwar**

### CODE REVIEW

**Comment by houseroad** [comment]
@onnxbot test this please

**Comment by houseroad** [comment]
I just checked our specification of PRelu, it's problematic. Since it's element-wise operator, we should follow the same broadcasting rules as other element-wise operator, such as Add, Sub, Pow, etc.
@tfujiwar could you also fix the specification and update the test cases?
@ebarsoum @yuanbyu @linkerzhang does this sound good to you?

**Comment by tfujiwar** [comment]
@houseroad Thanks for checking. Sure, I will.

**Comment by houseroad** [comment]
I will re-evaluate the changes in this PR, and give further comments. :-)

**Comment by tfujiwar** [comment]
@jamesr66a You are right. That case is similar with the following example and test case.
- https://github.com/onnx/onnx/pull/580/files#diff-def508ad6a02fca823d0a2debbbf65c2R5221
- https://github.com/onnx/onnx/pull/580/files#diff-a9ea2f3ab1d90865a1aa7acf36bd8f88R31

**Comment by jspisak** [comment]
@ebarsoum @linkerzhang @yuanbyu @lupesko Guys, this is a pretty easy one. Take a look, otherwise we'll just merge given this is just adding test cases.

**Comment by bddppq** [comment]
@houseroad @tfujiwar the broadcast support added here seems to be our old-style (i.e. with axis instead of following the one from numpy) version. Maybe let's don't add the broadcast in this PR but after #907 has settled?

**Comment by houseroad** [comment]
@bddppq yeah, let's wait until the we align to the numpy one. After that, we can keep polish this one.

**Comment by bddppq** [comment]
@tfujiwar @houseroad @linkerzhang I have updated this PR to follow #907

**Comment by houseroad** [comment]
@bddppq delete the stale cases generated by the old cases?

**Comment by bddppq** [comment]
@houseroad Good catch. I swear I had deleted them locally :-)

**Pull request merged**
