### PR TITLE
Fix Greater/LessOrEqual function definition

### PR DESCRIPTION
**Pull request by take-cheeze**

### CODE REVIEW

**Comment by postrational** [comment]
Thanks for catching this. Please sign the CLA, if you haven't yet.

**Comment by take-cheeze** [comment]
I don't know why CLA check isn't working...
Other PR is OK: https://github.com/onnx/onnx/pull/2640

**Comment by linkerzhang** [comment]
Indeed a good catch! 

One more question later is how to avoid this kind of bugs - validate function body's correctness. @jeremycochoy 

@take-cheeze can you create a new PR to work around the CLA issue please? this PR has to be merged before the 1.7 release - which is happening now.

**Comment by linkerzhang** [comment]
@chinhuang007

**Comment by jeremycochoy** [comment]
> Indeed a good catch!
> 
> One more question later is how to avoid this kind of bugs - validate function body's correctness. @jeremycochoy
> 
> @take-cheeze can you create a new PR to work around the CLA issue please? this PR has to be merged before the 1.7 release - which is happening now.

Ouch. 🤦‍♂ 

Ideally, you'd like to "run" the function using an existing runtime and check against the function tests to confirm consistency between definition and implementation. But it my require a lots of work to setup a CI running a ONNX backend and executing tests...

**Pull request closed without merging**
