### PR TITLE
Add several hyperbolic function ops.

### PR DESCRIPTION
**Pull request by kit1980**
Add acosh, asinh, atanh, cosh, sinh. These ops are used in CNTK and Tensorflow.

### CODE REVIEW

**Comment by kit1980** [comment]
Unrelated test_addmm failing, same as in another recent PR https://github.com/onnx/onnx/pull/1494

**Comment by kit1980** [comment]
Can someone looks at this?
The ops are very similar to the existing ops, and are needed to convert CNTK and TF models.

**Comment by ankkhedia** [comment]
@Roshrini @vandanavk

**Comment by ebarsoum** [comment]
@houseroad  and @bddppq can someone take a look?

**Comment by kit1980** [comment]
Rebased and updated the docs.

**Pull request merged**
