### PR TITLE
Fix input document of quantized operators

### PR DESCRIPTION
**Pull request by take-cheeze**
`s/scale/zero point/`

### CODE REVIEW

**Comment by fdwr** [comment]
@prasanthpul : Can we get an approving review for these small typos? TY.

**Comment by postrational** [comment]
This is good to merge, but we need to rerun the failing CI check.

**Comment by fdwr** [comment]
@postrational : Is there a magic incantation to do so? (short of a dummy push) It's not evident in the GitHub UI how to, and the circleci.com webpage has a "Rerun workflow" button that is grayed out. The error `test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_reshape Fatal Python error: Segmentation fault` isn't even related to this typo fix.

**Comment by postrational** [comment]
@fdwr A dummy push, or an update of the branch will trigger a full round of CI for you. I'm not sure if you can manually restart only Circle CI of you don't have permissions (I currently don't).

**Comment by prasanthpul** [comment]
@houseroad can you take a look at the Circle CI failure?

**Pull request merged**
